=== Kirin92/ditto/data/schema/v2/version/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "id": {
            "type": "integer"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "properties": {
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "version_group": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        }
    },
    "required": [
        "id",
        "name",
        "names",
        "version_group"
    ],
    "type": "object"
}

=== Kirin92/ditto/data/api/v2/version/25/index.json
{
    "id": 25,
    "name": "omega-ruby",
    "names": [
        {
            "language": {
                "name": "ja",
                "url": "http://127.0.0.1:8000/api/v2/language/1/"
            },
            "name": "\u30aa\u30e1\u30ac\u30eb\u30d3\u30fc"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://127.0.0.1:8000/api/v2/language/5/"
            },
            "name": "Rubis Om\u00e9ga"
        },
        {
            "language": {
                "name": "de",
                "url": "http://127.0.0.1:8000/api/v2/language/6/"
            },
            "name": "Omega Rubin"
        },
        {
            "language": {
                "name": "it",
                "url": "http://127.0.0.1:8000/api/v2/language/8/"
            },
            "name": "Rubino Omega"
        },
        {
            "language": {
                "name": "en",
                "url": "http://127.0.0.1:8000/api/v2/language/9/"
            },
            "name": "Omega Ruby"
        }
    ],
    "version_group": {
        "name": "omega-ruby-alpha-sapphire",
        "url": "http://127.0.0.1:8000/api/v2/version-group/16/"
    }
}
