=== Kirin92/ditto/data/schema/v2/pokemon/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "abilities": {
            "items": {
                "properties": {
                    "ability": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "is_hidden": {
                        "type": "boolean"
                    },
                    "slot": {
                        "type": "integer"
                    }
                },
                "required": [
                    "ability",
                    "is_hidden",
                    "slot"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "base_experience": {
            "type": "integer"
        },
        "forms": {
            "items": {
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "url"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "game_indices": {
            "items": {
                "properties": {
                    "game_index": {
                        "type": "integer"
                    },
                    "version": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "game_index",
                    "version"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "height": {
            "type": "integer"
        },
        "held_items": {
            "items": {
                "properties": {
                    "item": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "version_details": {
                        "items": {
                            "properties": {
                                "rarity": {
                                    "type": "integer"
                                },
                                "version": {
                                    "properties": {
                                        "name": {
                                            "type": "string"
                                        },
                                        "url": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "name",
                                        "url"
                                    ],
                                    "type": "object"
                                }
                            },
                            "required": [
                                "rarity",
                                "version"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    }
                },
                "required": [
                    "item",
                    "version_details"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "id": {
            "type": "integer"
        },
        "is_default": {
            "type": "boolean"
        },
        "location_area_encounters": {
            "type": "string"
        },
        "moves": {
            "items": {
                "properties": {
                    "move": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "version_group_details": {
                        "items": {
                            "properties": {
                                "level_learned_at": {
                                    "type": "integer"
                                },
                                "move_learn_method": {
                                    "properties": {
                                        "name": {
                                            "type": "string"
                                        },
                                        "url": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "name",
                                        "url"
                                    ],
                                    "type": "object"
                                },
                                "version_group": {
                                    "properties": {
                                        "name": {
                                            "type": "string"
                                        },
                                        "url": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "name",
                                        "url"
                                    ],
                                    "type": "object"
                                }
                            },
                            "required": [
                                "level_learned_at",
                                "move_learn_method",
                                "version_group"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    }
                },
                "required": [
                    "move",
                    "version_group_details"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "name": {
            "type": "string"
        },
        "order": {
            "type": "integer"
        },
        "species": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        },
        "sprites": {
            "properties": {
                "back_default": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "back_female": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "back_shiny": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "back_shiny_female": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "front_default": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "front_female": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "front_shiny": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "front_shiny_female": {
                    "type": [
                        "null",
                        "string"
                    ]
                }
            },
            "required": [
                "back_default",
                "back_female",
                "back_shiny",
                "back_shiny_female",
                "front_default",
                "front_female",
                "front_shiny",
                "front_shiny_female"
            ],
            "type": "object"
        },
        "stats": {
            "items": {
                "properties": {
                    "base_stat": {
                        "type": "integer"
                    },
                    "effort": {
                        "type": "integer"
                    },
                    "stat": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "base_stat",
                    "effort",
                    "stat"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "types": {
            "items": {
                "properties": {
                    "slot": {
                        "type": "integer"
                    },
                    "type": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "slot",
                    "type"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "weight": {
            "type": "integer"
        }
    },
    "required": [
        "abilities",
        "base_experience",
        "forms",
        "game_indices",
        "height",
        "held_items",
        "id",
        "is_default",
        "location_area_encounters",
        "moves",
        "name",
        "order",
        "species",
        "sprites",
        "stats",
        "types",
        "weight"
    ],
    "type": "object"
}

=== Kirin92/ditto/data/api/v2/pokemon/10079/index.json
{
    "abilities": [
        {
            "ability": {
                "name": "delta-stream",
                "url": "http://localhost/api/v2/ability/191/"
            },
            "is_hidden": false,
            "slot": 1
        }
    ],
    "base_experience": 351,
    "forms": [
        {
            "name": "rayquaza-mega",
            "url": "http://localhost/api/v2/pokemon-form/10181/"
        }
    ],
    "game_indices": [
        {
            "game_index": 814,
            "version": {
                "name": "omega-ruby",
                "url": "http://localhost/api/v2/version/25/"
            }
        }
    ],
    "height": 108,
    "held_items": [],
    "id": 10079,
    "is_default": false,
    "location_area_encounters": "/api/v2/pokemon/10079/encounters",
    "moves": [
        {
            "move": {
                "name": "swords-dance",
                "url": "http://localhost/api/v2/move/14/"
            },
            "version_group_details": [
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "http://localhost/api/v2/move-learn-method/4/"
                    },
                    "version_group": {
                        "name": "sun-moon",
                        "url": "http://localhost/api/v2/version-group/17/"
                    }
                },
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "http://localhost/api/v2/move-learn-method/4/"
                    },
                    "version_group": {
                        "name": "omega-ruby-alpha-sapphire",
                        "url": "http://localhost/api/v2/version-group/16/"
                    }
                }
            ]
        },
        {
            "move": {
                "name": "fly",
                "url": "http://localhost/api/v2/move/19/"
            },
            "version_group_details": [
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "http://localhost/api/v2/move-learn-method/4/"
                    },
                    "version_group": {
                        "name": "sun-moon",
                        "url": "http://localhost/api/v2/version-group/17/"
                    }
                },
                {
                    "level_learned_at": 65,
                    "move_learn_method": {
                        "name": "level-up",
                        "url": "http://localhost/api/v2/move-learn-method/1/"
                    },
                    "version_group": {
                        "name": "sun-moon",
                        "url": "http://localhost/api/v2/version-group/17/"
                    }
                },
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "http://localhost/api/v2/move-learn-method/4/"
                    },
                    "version_group": {
                        "name": "omega-ruby-alpha-sapphire",
                        "url": "http://localhost/api/v2/version-group/16/"
                    }
                },
                {
                    "level_learned_at": 65,
                    "move_learn_method": {
                        "name": "level-up",
                        "url": "http://localhost/api/v2/move-learn-method/1/"
                    },
                    "version_group": {
                        "name": "omega-ruby-alpha-sapphire",
                        "url": "http://localhost/api/v2/version-group/16/"
                    }
                }
            ]
        },
        {
            "move": {
                "name": "bind",
                "url": "http://localhost/api/v2/move/20/"
            },
            "version_group_details": [
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "tutor",
                        "url": "http://localhost/api/v2/move-learn-method/3/"
                    },
                    "version_group": {
                        "name": "omega-ruby-alpha-sapphire",
                        "url": "http://localhost/api/v2/version-group/16/"
                    }
                }
            ]
        },
        {
            "move": {
                "name": "roar",
                "url": "http://localhost/api/v2/move/46/"
            },
            "version_group_details": [
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "http://localhost/api/v2/move-learn-method/4/"
                    },
                    "version_group": {
                        "name": "sun-moon",
                        "url": "http://localhost/api/v2/version-group/17/"
                    }
                },
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "http://localhost/api/v2/move-learn-method/4/"
                    },
                    "version_group": {
                        "name": "omega-ruby-alpha-sapphire",
                        "url": "http://localhost/api/v2/version-group/16/"
                    }
                }
            ]
        },
        {
            "move": {
                "name": "flamethrower",
                "url": "http://localhost/api/v2/move/53/"
            },
            "version_group_details": [
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "http://localhost/api/v2/move-learn-method/4/"
                    },
                    "version_group": {
                        "name": "sun-moon",
                        "url": "http://localhost/api/v2/version-group/17/"
                    }
                },
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "http://localhost/api/v2/move-learn-method/4/"
                    },
                    "version_group": {
                        "name": "omega-ruby-alpha-sapphire",
                        "url": "http://localhost/api/v2/version-group/16/"
                    }
                }
            ]
        },
        {
            "move": {
                "name": "surf",
                "url": "http://localhost/api/v2/move/57/"
            },
            "version_group_details": [
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "http://localhost/api/v2/move-learn-method/4/"
                    },
                    "version_group": {
                        "name": "sun-moon",
                        "url": "http://localhost/api/v2/version-group/17/"
                    }
                },
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "http://localhost/api/v2/move-learn-method/4/"
                    },
                    "version_group": {
                        "name": "omega-ruby-alpha-sapphire",
                        "url": "http://localhost/api/v2/version-group/16/"
                    }
                }
            ]
        },
        {
            "move": {
                "name": "ice-beam",
                "url": "http://localhost/api/v2/move/58/"
            },
            "version_group_details": [
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "http://localhost/api/v2/move-learn-method/4/"
                    },
                    "version_group": {
                        "name": "sun-moon",
                        "url": "http://localhost/api/v2/version-group/17/"
                    }
                },
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "http://localhost/api/v2/move-learn-method/4/"
                    },
                    "version_group": {
                        "name": "omega-ruby-alpha-sapphire",
                        "url": "http://localhost/api/v2/version-group/16/"
                    }
                }
            ]
        },
        {
            "move": {
                "name": "blizzard",
                "url": "http://localhost/api/v2/move/59/"
            },
            "version_group_details": [
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "http://localhost/api/v2/move-learn-method/4/"
                    },
                    "version_group": {
                        "name": "sun-moon",
                        "url": "http://localhost/api/v2/version-group/17/"
                    }
                },
                {
                    "level_learned_at": 0,
                    "move_learn_method": {
                        "name": "machine",
                        "url": "http://localhost/api/v2/move-learn-method/4/"
                    },
                    "version_group": {
