=== Kirin92/ditto/data/schema/v2/characteristic/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "count": {
            "type": "integer"
        },
        "next": {
            "type": "null"
        },
        "previous": {
            "type": "null"
        },
        "results": {
            "items": {
                "properties": {
                    "url": {
                        "type": "string"
                    }
                },
                "required": [
                    "url"
                ],
                "type": "object"
            },
            "type": "array"
        }
    },
    "required": [
        "count",
        "next",
        "previous",
        "results"
    ],
    "type": "object"
}

=== Kirin92/ditto/api/v2/egg-group/limit=50.json
{"count":15,"previous":null,"results":[{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/egg-group\/1\/","name":"monster"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/egg-group\/2\/","name":"water1"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/egg-group\/3\/","name":"bug"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/egg-group\/4\/","name":"flying"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/egg-group\/5\/","name":"ground"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/egg-group\/6\/","name":"fairy"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/egg-group\/7\/","name":"plant"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/egg-group\/8\/","name":"humanshape"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/egg-group\/9\/","name":"water3"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/egg-group\/10\/","name":"mineral"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/egg-group\/11\/","name":"indeterminate"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/egg-group\/12\/","name":"water2"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/egg-group\/13\/","name":"ditto"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/egg-group\/14\/","name":"dragon"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/egg-group\/15\/","name":"no-eggs"}],"next":null}

=== Kirin92/ditto/api/v2/pokemon-habitat/limit=9.json
{
    "count": 9,
    "next": null,
    "previous": null,
    "results": [
        {
            "name": "cave",
            "url": "http://127.0.0.1:8000/api/v2/pokemon-habitat/1/"
        },
        {
            "name": "forest",
            "url": "http://127.0.0.1:8000/api/v2/pokemon-habitat/2/"
        },
        {
            "name": "grassland",
            "url": "http://127.0.0.1:8000/api/v2/pokemon-habitat/3/"
        },
        {
            "name": "mountain",
            "url": "http://127.0.0.1:8000/api/v2/pokemon-habitat/4/"
        },
        {
            "name": "rare",
            "url": "http://127.0.0.1:8000/api/v2/pokemon-habitat/5/"
        },
        {
            "name": "rough-terrain",
            "url": "http://127.0.0.1:8000/api/v2/pokemon-habitat/6/"
        },
        {
            "name": "sea",
            "url": "http://127.0.0.1:8000/api/v2/pokemon-habitat/7/"
        },
        {
            "name": "urban",
            "url": "http://127.0.0.1:8000/api/v2/pokemon-habitat/8/"
        },
        {
            "name": "waters-edge",
            "url": "http://127.0.0.1:8000/api/v2/pokemon-habitat/9/"
        }
    ]
}

=== Kirin92/ditto/api/v2/pokemon/limit=50.json
{"count":811,"previous":null,"results":[{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/1\/","name":"bulbasaur"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/2\/","name":"ivysaur"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/3\/","name":"venusaur"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/4\/","name":"charmander"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/5\/","name":"charmeleon"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/6\/","name":"charizard"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/7\/","name":"squirtle"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/8\/","name":"wartortle"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/9\/","name":"blastoise"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/10\/","name":"caterpie"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/11\/","name":"metapod"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/12\/","name":"butterfree"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/13\/","name":"weedle"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/14\/","name":"kakuna"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/15\/","name":"beedrill"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/16\/","name":"pidgey"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/17\/","name":"pidgeotto"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/18\/","name":"pidgeot"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/19\/","name":"rattata"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/20\/","name":"raticate"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/21\/","name":"spearow"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/22\/","name":"fearow"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/23\/","name":"ekans"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/24\/","name":"arbok"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/25\/","name":"pikachu"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/26\/","name":"raichu"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/27\/","name":"sandshrew"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/28\/","name":"sandslash"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/29\/","name":"nidoran-f"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/30\/","name":"nidorina"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/31\/","name":"nidoqueen"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/32\/","name":"nidoran-m"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/33\/","name":"nidorino"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/34\/","name":"nidoking"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/35\/","name":"clefairy"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/36\/","name":"clefable"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/37\/","name":"vulpix"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/38\/","name":"ninetales"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/39\/","name":"jigglypuff"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/40\/","name":"wigglytuff"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/41\/","name":"zubat"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/42\/","name":"golbat"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/43\/","name":"oddish"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/44\/","name":"gloom"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/45\/","name":"vileplume"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/46\/","name":"paras"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/47\/","name":"parasect"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/48\/","name":"venonat"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/49\/","name":"venomoth"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/50\/","name":"diglett"}],"next":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/?limit=50&offset=50"}

=== Kirin92/ditto/data/api/v2/egg-group/index.json
{
    "count": 15,
    "next": null,
    "previous": null,
    "results": [
        {
            "name": "monster",
            "url": "http://localhost/api/v2/egg-group/1/"
        },
        {
            "name": "water1",
            "url": "http://localhost/api/v2/egg-group/2/"
        },
        {
            "name": "bug",
            "url": "http://localhost/api/v2/egg-group/3/"
        },
        {
            "name": "flying",
            "url": "http://localhost/api/v2/egg-group/4/"
        },
        {
            "name": "ground",
            "url": "http://localhost/api/v2/egg-group/5/"
        },
        {
            "name": "fairy",
            "url": "http://localhost/api/v2/egg-group/6/"
        },
        {
            "name": "plant",
            "url": "http://localhost/api/v2/egg-group/7/"
        },
        {
            "name": "humanshape",
            "url": "http://localhost/api/v2/egg-group/8/"
        },
        {
            "name": "water3",
            "url": "http://localhost/api/v2/egg-group/9/"
        },
        {
            "name": "mineral",
            "url": "http://localhost/api/v2/egg-group/10/"
        },
        {
            "name": "indeterminate",
            "url": "http://localhost/api/v2/egg-group/11/"
        },
        {
            "name": "water2",
            "url": "http://localhost/api/v2/egg-group/12/"
        },
        {
            "name": "ditto",
            "url": "http://localhost/api/v2/egg-group/13/"
        },
        {
            "name": "dragon",
            "url": "http://localhost/api/v2/egg-group/14/"
        },
        {
            "name": "no-eggs",
            "url": "http://localhost/api/v2/egg-group/15/"
        }
    ]
}

=== Kirin92/ditto/api/v2/move-learn-method/index.json
{"count":10,"previous":null,"results":[{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move-learn-method\/1\/","name":"level-up"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move-learn-method\/2\/","name":"egg"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move-learn-method\/3\/","name":"tutor"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move-learn-method\/4\/","name":"machine"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move-learn-method\/5\/","name":"stadium-surfing-pikachu"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move-learn-method\/6\/","name":"light-ball-egg"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move-learn-method\/7\/","name":"colosseum-purification"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move-learn-method\/8\/","name":"xd-shadow"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move-learn-method\/9\/","name":"xd-purification"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move-learn-method\/10\/","name":"form-change"}],"next":null}

=== Kirin92/ditto/data/api/v2/move-damage-class/index.json
{
    "count": 3,
    "next": null,
    "previous": null,
    "results": [
        {
            "name": "status",
            "url": "http://localhost/api/v2/move-damage-class/1/"
        },
        {
            "name": "physical",
            "url": "http://localhost/api/v2/move-damage-class/2/"
        },
        {
            "name": "special",
            "url": "http://localhost/api/v2/move-damage-class/3/"
        }
    ]
}
