=== Kirin92/ditto/data/schema/v2/item-category/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "id": {
            "type": "integer"
        },
        "items": {
            "items": {
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "url"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "properties": {
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "pocket": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        }
    },
    "required": [
        "id",
        "items",
        "name",
        "names",
        "pocket"
    ],
    "type": "object"
}

=== Kirin92/ditto/data/api/v2/item-category/11/index.json
{
    "id": 11,
    "items": [
        {
            "name": "poke-doll",
            "url": "http://localhost/api/v2/item/63/"
        },
        {
            "name": "fluffy-tail",
            "url": "http://localhost/api/v2/item/64/"
        },
        {
            "name": "black-flute",
            "url": "http://localhost/api/v2/item/68/"
        },
        {
            "name": "white-flute",
            "url": "http://localhost/api/v2/item/69/"
        },
        {
            "name": "super-repel",
            "url": "http://localhost/api/v2/item/76/"
        },
        {
            "name": "max-repel",
            "url": "http://localhost/api/v2/item/77/"
        },
        {
            "name": "escape-rope",
            "url": "http://localhost/api/v2/item/78/"
        },
        {
            "name": "repel",
            "url": "http://localhost/api/v2/item/79/"
        },
        {
            "name": "poke-toy",
            "url": "http://localhost/api/v2/item/618/"
        }
    ],
    "name": "spelunking",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "Spelunking"
        }
    ],
    "pocket": {
        "name": "misc",
        "url": "http://localhost/api/v2/item-pocket/1/"
    }
}
