=== Kirin92/ditto/data/schema/v2/contest-effect/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "appeal": {
            "type": "integer"
        },
        "effect_entries": {
            "items": {
                "properties": {
                    "effect": {
                        "type": "string"
                    },
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "effect",
                    "language"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "flavor_text_entries": {
            "items": {
                "properties": {
                    "flavor_text": {
                        "type": "string"
                    },
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "flavor_text",
                    "language"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "id": {
            "type": "integer"
        },
        "jam": {
            "type": "integer"
        }
    },
    "required": [
        "appeal",
        "effect_entries",
        "flavor_text_entries",
        "id",
        "jam"
    ],
    "type": "object"
}

=== Kirin92/ditto/data/api/v2/contest-effect/30/index.json
{
    "appeal": 3,
    "effect_entries": [
        {
            "effect": "User will go first next turn.",
            "language": {
                "name": "en",
                "url": "http://127.0.0.1:8000/api/v2/language/9/"
            }
        }
    ],
    "flavor_text_entries": [
        {
            "flavor_text": "The next appeal can be made earlier next turn.",
            "language": {
                "name": "en",
                "url": "http://127.0.0.1:8000/api/v2/language/9/"
            }
        }
    ],
    "id": 30,
    "jam": 0
}

=== Kirin92/ditto/api/v2/contest-effect/25/index.json
{"effect_entries":[{"effect":"Randomly earns one, two, four, or eight points.","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}}],"jam":0,"appeal":1,"flavor_text_entries":[{"flavor_text":"The appeal's quality depends on its timing.","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}}],"id":25}

=== Kirin92/ditto/api/v2/contest-effect/31/index.json
{"effect_entries":[{"effect":"User will go last next turn.","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}}],"jam":0,"appeal":3,"flavor_text_entries":[{"flavor_text":"The next appeal can be made later next turn.","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}}],"id":31}
