=== Kirin92/ditto/data/schema/v2/location-area/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "encounter_method_rates": {
            "items": {
                "properties": {
                    "encounter_method": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "version_details": {
                        "items": {
                            "properties": {
                                "rate": {
                                    "type": "integer"
                                },
                                "version": {
                                    "properties": {
                                        "name": {
                                            "type": "string"
                                        },
                                        "url": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "name",
                                        "url"
                                    ],
                                    "type": "object"
                                }
                            },
                            "required": [
                                "rate",
                                "version"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    }
                },
                "required": [
                    "encounter_method",
                    "version_details"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "game_index": {
            "type": "integer"
        },
        "id": {
            "type": "integer"
        },
        "location": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "properties": {
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "pokemon_encounters": {
            "items": {
                "properties": {
                    "pokemon": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "version_details": {
                        "items": {
                            "properties": {
                                "encounter_details": {
                                    "items": {
                                        "properties": {
                                            "chance": {
                                                "type": "integer"
                                            },
                                            "condition_values": {
                                                "items": {
                                                    "properties": {
                                                        "name": {
                                                            "type": "string"
                                                        },
                                                        "url": {
                                                            "type": "string"
                                                        }
                                                    },
                                                    "required": [
                                                        "name",
                                                        "url"
                                                    ],
                                                    "type": "object"
                                                },
                                                "type": "array"
                                            },
                                            "max_level": {
                                                "type": "integer"
                                            },
                                            "method": {
                                                "properties": {
                                                    "name": {
                                                        "type": "string"
                                                    },
                                                    "url": {
                                                        "type": "string"
                                                    }
                                                },
                                                "required": [
                                                    "name",
                                                    "url"
                                                ],
                                                "type": "object"
                                            },
                                            "min_level": {
                                                "type": "integer"
                                            }
                                        },
                                        "required": [
                                            "chance",
                                            "condition_values",
                                            "max_level",
                                            "method",
                                            "min_level"
                                        ],
                                        "type": "object"
                                    },
                                    "type": "array"
                                },
                                "max_chance": {
                                    "type": "integer"
                                },
                                "version": {
                                    "properties": {
                                        "name": {
                                            "type": "string"
                                        },
                                        "url": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "name",
                                        "url"
                                    ],
                                    "type": "object"
                                }
                            },
                            "required": [
                                "encounter_details",
                                "max_chance",
                                "version"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    }
                },
                "required": [
                    "pokemon",
                    "version_details"
                ],
                "type": "object"
            },
            "type": "array"
        }
    },
    "required": [
        "encounter_method_rates",
        "game_index",
        "id",
        "location",
        "name",
        "names",
        "pokemon_encounters"
    ],
    "type": "object"
}

=== Kirin92/ditto/api/v2/location-area/746/index.json
{"names":[{"name":"Unknown Area 317","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}}],"name":"frost-cavern-unknown-area-317","encounter_method_rates":[],"location":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/location\/640\/","name":"frost-cavern"},"pokemon_encounters":[{"version_details":[{"max_chance":16,"version":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version\/23\/","name":"x"},"encounter_details":[{"min_level":38,"max_level":38,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":39,"max_level":39,"condition_values":[],"chance":5,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":40,"max_level":40,"condition_values":[],"chance":1,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}}]},{"max_chance":16,"version":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version\/24\/","name":"y"},"encounter_details":[{"min_level":40,"max_level":40,"condition_values":[],"chance":1,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":39,"max_level":39,"condition_values":[],"chance":5,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":38,"max_level":38,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}}]}],"pokemon":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/93\/","name":"haunter"}},{"version_details":[{"max_chance":20,"version":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version\/23\/","name":"x"},"encounter_details":[{"min_level":39,"max_level":39,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":40,"max_level":40,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}}]},{"max_chance":20,"version":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version\/24\/","name":"y"},"encounter_details":[{"min_level":40,"max_level":40,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":39,"max_level":39,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}}]}],"pokemon":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/124\/","name":"jynx"}},{"version_details":[{"max_chance":20,"version":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version\/23\/","name":"x"},"encounter_details":[{"min_level":38,"max_level":38,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":39,"max_level":39,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}}]},{"max_chance":20,"version":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version\/24\/","name":"y"},"encounter_details":[{"min_level":39,"max_level":39,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":38,"max_level":38,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}}]}],"pokemon":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/221\/","name":"piloswine"}},{"version_details":[{"max_chance":20,"version":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version\/23\/","name":"x"},"encounter_details":[{"min_level":39,"max_level":39,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":40,"max_level":40,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}}]},{"max_chance":20,"version":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version\/24\/","name":"y"},"encounter_details":[{"min_level":40,"max_level":40,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":39,"max_level":39,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}}]}],"pokemon":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/614\/","name":"beartic"}},{"version_details":[{"max_chance":4,"version":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version\/23\/","name":"x"},"encounter_details":[{"min_level":40,"max_level":40,"condition_values":[],"chance":4,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}}]},{"max_chance":4,"version":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version\/24\/","name":"y"},"encounter_details":[{"min_level":40,"max_level":40,"condition_values":[],"chance":4,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}}]}],"pokemon":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/615\/","name":"cryogonal"}},{"version_details":[{"max_chance":20,"version":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version\/23\/","name":"x"},"encounter_details":[{"min_level":39,"max_level":39,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":40,"max_level":40,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}}]},{"max_chance":20,"version":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version\/24\/","name":"y"},"encounter_details":[{"min_level":40,"max_level":40,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":39,"max_level":39,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}}]}],"pokemon":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/712\/","name":"bergmite"}}],"id":746,"game_index":0}

=== Kirin92/ditto/api/v2/location-area/452/index.json
{"names":[{"name":"","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}}],"name":"weepth-chamber-area","encounter_method_rates":[{"encounter_method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"},"version_details":[{"rate":7,"version":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version\/11\/","name":"leafgreen"}},{"rate":7,"version":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version\/10\/","name":"firered"}}]}],"location":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/location\/493\/","name":"weepth-chamber"},"pokemon_encounters":[{"version_details":[{"max_chance":100,"version":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version\/10\/","name":"firered"},"encounter_details":[{"min_level":25,"max_level":25,"condition_values":[],"chance":1,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":25,"max_level":25,"condition_values":[],"chance":1,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":25,"max_level":25,"condition_values":[],"chance":4,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":25,"max_level":25,"condition_values":[],"chance":4,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":25,"max_level":25,"condition_values":[],"chance":5,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":25,"max_level":25,"condition_values":[],"chance":5,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":25,"max_level":25,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":25,"max_level":25,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":25,"max_level":25,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":25,"max_level":25,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":25,"max_level":25,"condition_values":[],"chance":20,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":25,"max_level":25,"condition_values":[],"chance":20,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}}]},{"max_chance":100,"version":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version\/11\/","name":"leafgreen"},"encounter_details":[{"min_level":25,"max_level":25,"condition_values":[],"chance":1,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":25,"max_level":25,"condition_values":[],"chance":1,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":25,"max_level":25,"condition_values":[],"chance":4,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":25,"max_level":25,"condition_values":[],"chance":4,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":25,"max_level":25,"condition_values":[],"chance":5,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":25,"max_level":25,"condition_values":[],"chance":5,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":25,"max_level":25,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":25,"max_level":25,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":25,"max_level":25,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":25,"max_level":25,"condition_values":[],"chance":10,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":25,"max_level":25,"condition_values":[],"chance":20,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}},{"min_level":25,"max_level":25,"condition_values":[],"chance":20,"method":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-method\/1\/","name":"walk"}}]}],"pokemon":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokemon\/201\/","name":"unown"}}],"id":452,"game_index":2}

=== Kirin92/ditto/api/v2/location-area/444/index.json
{
    "encounter_method_rates": [
        {
            "encounter_method": {
                "name": "walk",
                "url": "http://127.0.0.1:8000/api/v2/encounter-method/1/"
            },
            "version_details": [
                {
                    "rate": 7,
                    "version": {
                        "name": "emerald",
                        "url": "http://127.0.0.1:8000/api/v2/version/9/"
                    }
                }
            ]
        }
    ],
    "game_index": 117,
    "id": 444,
    "location": {
        "name": "hoenn-altering-cave",
        "url": "http://127.0.0.1:8000/api/v2/location/490/"
    },
    "name": "hoenn-altering-cave-d",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://127.0.0.1:8000/api/v2/language/9/"
            },
            "name": "d"
        }
    ],
    "pokemon_encounters": [
        {
            "pokemon": {
                "name": "houndour",
                "url": "http://127.0.0.1:8000/api/v2/pokemon/228/"
            },
            "version_details": [
                {
                    "encounter_details": [
                        {
                            "chance": 20,
                            "condition_values": [],
                            "max_level": 16,
                            "method": {
                                "name": "walk",
                                "url": "http://127.0.0.1:8000/api/v2/encounter-method/1/"
                            },
                            "min_level": 16
                        },
                        {
                            "chance": 20,
                            "condition_values": [],
                            "max_level": 18,
                            "method": {
                                "name": "walk",
                                "url": "http://127.0.0.1:8000/api/v2/encounter-method/1/"
                            },
                            "min_level": 18
                        },
                        {
                            "chance": 10,
                            "condition_values": [],
                            "max_level": 14,
                            "method": {
                                "name": "walk",
                                "url": "http://127.0.0.1:8000/api/v2/encounter-method/1/"
                            },
                            "min_level": 14
                        },
                        {
                            "chance": 10,
                            "condition_values": [],
                            "max_level": 20,
                            "method": {
                                "name": "walk",
                                "url": "http://127.0.0.1:8000/api/v2/encounter-method/1/"
                            },
                            "min_level": 20
                        },
                        {
                            "chance": 10,
                            "condition_values": [],
                            "max_level": 16,
                            "method": {
                                "name": "walk",
                                "url": "http://127.0.0.1:8000/api/v2/encounter-method/1/"
                            },
                            "min_level": 16
                        },
                        {
                            "chance": 10,
                            "condition_values": [],
                            "max_level": 18,
                            "method": {
                                "name": "walk",
                                "url": "http://127.0.0.1:8000/api/v2/encounter-method/1/"
                            },
                            "min_level": 18
                        },
                        {
                            "chance": 5,
                            "condition_values": [],
                            "max_level": 22,
                            "method": {
                                "name": "walk",
                                "url": "http://127.0.0.1:8000/api/v2/encounter-method/1/"
                            },
                            "min_level": 22
                        },
                        {
                            "chance": 5,
                            "condition_values": [],
                            "max_level": 12,
                            "method": {
                                "name": "walk",
                                "url": "http://127.0.0.1:8000/api/v2/encounter-method/1/"
                            },
                            "min_level": 12
                        },
                        {
                            "chance": 4,
                            "condition_values": [],
                            "max_level": 14,
                            "method": {
                                "name": "walk",
                                "url": "http://127.0.0.1:8000/api/v2/encounter-method/1/"
                            },
                            "min_level": 14
                        },
                        {
                            "chance": 4,
                            "condition_values": [],
                            "max_level": 20,
                            "method": {
                                "name": "walk",
                                "url": "http://127.0.0.1:8000/api/v2/encounter-method/1/"
                            },
                            "min_level": 20
                        },
                        {
                            "chance": 1,
                            "condition_values": [],
                            "max_level": 14,
                            "method": {
                                "name": "walk",
                                "url": "http://127.0.0.1:8000/api/v2/encounter-method/1/"
                            },
                            "min_level": 14
                        },
                        {
                            "chance": 1,
                            "condition_values": [],
                            "max_level": 20,
                            "method": {
                                "name": "walk",
                                "url": "http://127.0.0.1:8000/api/v2/encounter-method/1/"
                            },
                            "min_level": 20
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "emerald",
                        "url": "http://127.0.0.1:8000/api/v2/version/9/"
                    }
                }
            ]
        }
    ]
}
