=== Kirin92/ditto/data/schema/v2/version-group/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "generation": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        },
        "id": {
            "type": "integer"
        },
        "move_learn_methods": {
            "items": {
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "url"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "name": {
            "type": "string"
        },
        "order": {
            "type": "integer"
        },
        "pokedexes": {
            "items": {
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "url"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "regions": {
            "items": {
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "url"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "versions": {
            "items": {
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "url"
                ],
                "type": "object"
            },
            "type": "array"
        }
    },
    "required": [
        "generation",
        "id",
        "move_learn_methods",
        "name",
        "order",
        "pokedexes",
        "regions",
        "versions"
    ],
    "type": "object"
}

=== Kirin92/ditto/api/v2/version-group/9/index.json
{
    "generation": {
        "name": "generation-iv",
        "url": "http://127.0.0.1:8000/api/v2/generation/4/"
    },
    "id": 9,
    "move_learn_methods": [
        {
            "name": "level-up",
            "url": "http://127.0.0.1:8000/api/v2/move-learn-method/1/"
        },
        {
            "name": "egg",
            "url": "http://127.0.0.1:8000/api/v2/move-learn-method/2/"
        },
        {
            "name": "tutor",
            "url": "http://127.0.0.1:8000/api/v2/move-learn-method/3/"
        },
        {
            "name": "machine",
            "url": "http://127.0.0.1:8000/api/v2/move-learn-method/4/"
        },
        {
            "name": "light-ball-egg",
            "url": "http://127.0.0.1:8000/api/v2/move-learn-method/6/"
        },
        {
            "name": "form-change",
            "url": "http://127.0.0.1:8000/api/v2/move-learn-method/10/"
        }
    ],
    "name": "platinum",
    "order": 11,
    "pokedexes": [
        {
            "name": "extended-sinnoh",
            "url": "http://127.0.0.1:8000/api/v2/pokedex/6/"
        }
    ],
    "regions": [
        {
            "name": "sinnoh",
            "url": "http://127.0.0.1:8000/api/v2/region/4/"
        }
    ],
    "versions": [
        {
            "name": "platinum",
            "url": "http://127.0.0.1:8000/api/v2/version/14/"
        }
    ]
}
