=== Kirin92/ditto/data/schema/v2/pokemon-species/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "base_happiness": {
            "type": "integer"
        },
        "capture_rate": {
            "type": "integer"
        },
        "color": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        },
        "egg_groups": {
            "items": {
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "url"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "evolution_chain": {
            "properties": {
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "url"
            ],
            "type": "object"
        },
        "evolves_from_species": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "url": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "name",
                        "url"
                    ],
                    "type": "object"
                }
            ]
        },
        "flavor_text_entries": {
            "items": {
                "properties": {
                    "flavor_text": {
                        "type": "string"
                    },
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "version": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "flavor_text",
                    "language",
                    "version"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "form_descriptions": {
            "items": {
                "properties": {
                    "description": {
                        "type": "string"
                    },
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "description",
                    "language"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "forms_switchable": {
            "type": "boolean"
        },
        "gender_rate": {
            "type": "integer"
        },
        "genera": {
            "items": {
                "properties": {
                    "genus": {
                        "type": "string"
                    },
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "genus",
                    "language"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "generation": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        },
        "growth_rate": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        },
        "habitat": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "url": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "name",
                        "url"
                    ],
                    "type": "object"
                }
            ]
        },
        "has_gender_differences": {
            "type": "boolean"
        },
        "hatch_counter": {
            "type": "integer"
        },
        "id": {
            "type": "integer"
        },
        "is_baby": {
            "type": "boolean"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "properties": {
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "order": {
            "type": "integer"
        },
        "pal_park_encounters": {
            "items": {
                "properties": {
                    "area": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "base_score": {
                        "type": "integer"
                    },
                    "rate": {
                        "type": "integer"
                    }
                },
                "required": [
                    "area",
                    "base_score",
                    "rate"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "pokedex_numbers": {
            "items": {
                "properties": {
                    "entry_number": {
                        "type": "integer"
                    },
                    "pokedex": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "entry_number",
                    "pokedex"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "shape": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        },
        "varieties": {
            "items": {
                "properties": {
                    "is_default": {
                        "type": "boolean"
                    },
                    "pokemon": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "is_default",
                    "pokemon"
                ],
                "type": "object"
            },
            "type": "array"
        }
    },
    "required": [
        "base_happiness",
        "capture_rate",
        "color",
        "egg_groups",
        "evolution_chain",
        "evolves_from_species",
        "flavor_text_entries",
        "form_descriptions",
        "forms_switchable",
        "gender_rate",
        "genera",
        "generation",
        "growth_rate",
        "habitat",
        "has_gender_differences",
        "hatch_counter",
        "id",
        "is_baby",
        "name",
        "names",
        "order",
        "pal_park_encounters",
        "pokedex_numbers",
        "shape",
        "varieties"
    ],
    "type": "object"
}

=== Kirin92/ditto/data/api/v2/pokemon-species/143/index.json
{
    "base_happiness": 70,
    "capture_rate": 25,
    "color": {
        "name": "black",
        "url": "http://localhost/api/v2/pokemon-color/1/"
    },
    "egg_groups": [
        {
            "name": "monster",
            "url": "http://localhost/api/v2/egg-group/1/"
        }
    ],
    "evolution_chain": {
        "url": "http://localhost/api/v2/evolution-chain/72/"
    },
    "evolves_from_species": {
        "name": "munchlax",
        "url": "http://localhost/api/v2/pokemon-species/446/"
    },
    "flavor_text_entries": [
        {
            "flavor_text": "\u98df\u3079\u3066\u3000\u5bdd\u3066\u306e\u3000\u7e70\u308a\u8fd4\u3057\u3067\u3000\uff11\u65e5\u304c\u3000\u7d42\u308f\u308b\u3002\n\u5927\u304d\u306a\u3000\u304a\u8179\u306e\u3000\u4e0a\u3092\u3000\u904a\u3073\u5834\u306b\u3000\u3057\u3066\u3044\u308b\n\u5b50\u3069\u3082\u305f\u3061\u3082\u3000\u3044\u308b\u307b\u3069\u3000\u5927\u4eba\u3057\u3044\u3000\u30dd\u30b1\u30e2\u30f3\u3060\u3002",
            "language": {
                "name": "ja-kanji",
                "url": "http://localhost/api/v2/language/11/"
            },
            "version": {
                "name": "alpha-sapphire",
                "url": "http://localhost/api/v2/version/26/"
            }
        },
        {
            "flavor_text": "Snorlax\u2019s typical day consists of nothing more than eating and\nsleeping. It is such a docile Pok\u00e9mon that there are children\nwho use its expansive belly as a place to play.",
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "version": {
                "name": "alpha-sapphire",
                "url": "http://localhost/api/v2/version/26/"
            }
        },
        {
            "flavor_text": "La giornata tipica di Snorlax consiste in nient\u2019altro che\nmangiare e dormire. \u00c8 un Pok\u00e9mon cos\u00ec docile che\ni bambini usano la sua enorme pancia come parco giochi.",
            "language": {
                "name": "it",
                "url": "http://localhost/api/v2/language/8/"
            },
            "version": {
                "name": "alpha-sapphire",
                "url": "http://localhost/api/v2/version/26/"
            }
        },
        {
            "flavor_text": "Un d\u00eda cualquiera en la vida de Snorlax consiste en comer y\ndormir. Es un Pok\u00e9mon tan d\u00f3cil que es f\u00e1cil ver ni\u00f1os usando\nla gran panza que tiene como lugar de juegos.",
            "language": {
                "name": "es",
                "url": "http://localhost/api/v2/language/7/"
            },
            "version": {
                "name": "alpha-sapphire",
                "url": "http://localhost/api/v2/version/26/"
            }
        },
        {
            "flavor_text": "Der typische Tagesablauf von Relaxo besteht lediglich aus\nEssen und Schlafen. Es ist so zutraulich, dass Kinder seinen\ndicken Bauch als Platz zum Spielen nutzen.",
            "language": {
                "name": "de",
                "url": "http://localhost/api/v2/language/6/"
            },
            "version": {
                "name": "alpha-sapphire",
                "url": "http://localhost/api/v2/version/26/"
            }
        },
        {
            "flavor_text": "Les journ\u00e9es de Ronflex se r\u00e9sument aux repas et aux siestes.\nC\u2019est un Pok\u00e9mon tellement gentil que les enfants n\u2019h\u00e9sitent\npas \u00e0 jouer sur son \u00e9norme ventre.",
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "version": {
                "name": "alpha-sapphire",
                "url": "http://localhost/api/v2/version/26/"
            }
        },
        {
            "flavor_text": "\uba39\uace0 \uc790\ub294 \uac83\uc744 \ubc18\ubcf5\ud558\ub2e4 \ud558\ub8e8\uac00 \ub05d\ub09c\ub2e4.\n\ud070 \ubc30 \uc704\ub97c \ub180\uc774\ud130\ub85c \uc0bc\uc740 \uc544\uc774\ub4e4\uc774\n\uc788\uc744 \uc815\ub3c4\ub85c \uc58c\uc804\ud55c \ud3ec\ucf13\ubaac\uc774\ub2e4.",
            "language": {
                "name": "ko",
                "url": "http://localhost/api/v2/language/3/"
            },
            "version": {
                "name": "alpha-sapphire",
                "url": "http://localhost/api/v2/version/26/"
            }
        },
        {
            "flavor_text": "\u305f\u3079\u3066\u3000\u306d\u3066\u306e\u3000\u304f\u308a\u304b\u3048\u3057\u3067\u3000\uff11\u306b\u3061\u304c\u3000\u304a\u308f\u308b\u3002\n\u304a\u304a\u304d\u306a\u3000\u304a\u306a\u304b\u306e\u3000\u3046\u3048\u3092\u3000\u3042\u305d\u3073\u3070\u306b\u3000\u3057\u3066\u3044\u308b\n\u3053\u3069\u3082\u305f\u3061\u3082\u3000\u3044\u308b\u307b\u3069\u3000\u304a\u3068\u306a\u3057\u3044\u3000\u30dd\u30b1\u30e2\u30f3\u3060\u3002",
            "language": {
                "name": "ja",
                "url": "http://localhost/api/v2/language/1/"
            },
            "version": {
                "name": "alpha-sapphire",
                "url": "http://localhost/api/v2/version/26/"
            }
        },
        {
            "flavor_text": "\u98df\u3079\u3066\u3000\u5bdd\u3066\u306e\u3000\u7e70\u308a\u8fd4\u3057\u3067\u3000\uff11\u65e5\u304c\u3000\u7d42\u308f\u308b\u3002\n\u5927\u304d\u306a\u3000\u304a\u8179\u306e\u3000\u4e0a\u3092\u3000\u904a\u3073\u5834\u306b\u3000\u3057\u3066\u3044\u308b\n\u5b50\u3069\u3082\u305f\u3061\u3082\u3000\u3044\u308b\u307b\u3069\u3000\u5927\u4eba\u3057\u3044\u3000\u30dd\u30b1\u30e2\u30f3\u3060\u3002",
            "language": {
                "name": "ja-kanji",
                "url": "http://localhost/api/v2/language/11/"
            },
            "version": {
                "name": "omega-ruby",
                "url": "http://localhost/api/v2/version/25/"
            }
        },
        {
            "flavor_text": "Snorlax\u2019s typical day consists of nothing more than eating and\nsleeping. It is such a docile Pok\u00e9mon that there are children\nwho use its expansive belly as a place to play.",
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "version": {
                "name": "omega-ruby",
                "url": "http://localhost/api/v2/version/25/"
            }
        },
        {
            "flavor_text": "La giornata tipica di Snorlax consiste in nient\u2019altro che\nmangiare e dormire. \u00c8 un Pok\u00e9mon cos\u00ec docile che\ni bambini usano la sua enorme pancia come parco giochi.",
            "language": {
                "name": "it",
                "url": "http://localhost/api/v2/language/8/"
            },
            "version": {
                "name": "omega-ruby",
                "url": "http://localhost/api/v2/version/25/"
            }
        },
        {
            "flavor_text": "Un d\u00eda cualquiera en la vida de Snorlax consiste en comer y\ndormir. Es un Pok\u00e9mon tan d\u00f3cil que es f\u00e1cil ver ni\u00f1os usando\nla gran panza que tiene como lugar de juegos.",
            "language": {
                "name": "es",
                "url": "http://localhost/api/v2/language/7/"
            },
            "version": {
                "name": "omega-ruby",
                "url": "http://localhost/api/v2/version/25/"
            }
        },
        {
            "flavor_text": "Der typische Tagesablauf von Relaxo besteht lediglich aus\nEssen und Schlafen. Es ist so zutraulich, dass Kinder seinen\ndicken Bauch als Platz zum Spielen nutzen.",
            "language": {
                "name": "de",
                "url": "http://localhost/api/v2/language/6/"
            },
            "version": {
                "name": "omega-ruby",
                "url": "http://localhost/api/v2/version/25/"
            }
        },
        {
            "flavor_text": "Les journ\u00e9es de Ronflex se r\u00e9sument aux repas et aux siestes.\nC\u2019est un Pok\u00e9mon tellement gentil que les enfants n\u2019h\u00e9sitent\npas \u00e0 jouer sur son \u00e9norme ventre.",
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "version": {
                "name": "omega-ruby",
                "url": "http://localhost/api/v2/version/25/"
            }
        },
        {
            "flavor_text": "\uba39\uace0 \uc790\ub294 \uac83\uc744 \ubc18\ubcf5\ud558\ub2e4 \ud558\ub8e8\uac00 \ub05d\ub09c\ub2e4.\n\ud070 \ubc30 \uc704\ub97c \ub180\uc774\ud130\ub85c \uc0bc\uc740 \uc544\uc774\ub4e4\uc774\n\uc788\uc744 \uc815\ub3c4\ub85c \uc58c\uc804\ud55c \ud3ec\ucf13\ubaac\uc774\ub2e4.",
            "language": {
                "name": "ko",
                "url": "http://localhost/api/v2/language/3/"
            },
            "version": {
                "name": "omega-ruby",
                "url": "http://localhost/api/v2/version/25/"
            }
        },
        {
            "flavor_text": "\u305f\u3079\u3066\u3000\u306d\u3066\u306e\u3000\u304f\u308a\u304b\u3048\u3057\u3067\u3000\uff11\u306b\u3061\u304c\u3000\u304a\u308f\u308b\u3002\n\u304a\u304a\u304d\u306a\u3000\u304a\u306a\u304b\u306e\u3000\u3046\u3048\u3092\u3000\u3042\u305d\u3073\u3070\u306b\u3000\u3057\u3066\u3044\u308b\n\u3053\u3069\u3082\u305f\u3061\u3082\u3000\u3044\u308b\u307b\u3069\u3000\u304a\u3068\u306a\u3057\u3044\u3000\u30dd\u30b1\u30e2\u30f3\u3060\u3002",
            "language": {
                "name": "ja",
                "url": "http://localhost/api/v2/language/1/"
            },
            "version": {
                "name": "omega-ruby",
                "url": "http://localhost/api/v2/version/25/"
            }
        },
        {
