=== Kirin92/ditto/data/schema/v2/nature/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "decreased_stat": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "url": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "name",
                        "url"
                    ],
                    "type": "object"
                }
            ]
        },
        "hates_flavor": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "url": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "name",
                        "url"
                    ],
                    "type": "object"
                }
            ]
        },
        "id": {
            "type": "integer"
        },
        "increased_stat": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "url": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "name",
                        "url"
                    ],
                    "type": "object"
                }
            ]
        },
        "likes_flavor": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "url": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "name",
                        "url"
                    ],
                    "type": "object"
                }
            ]
        },
        "move_battle_style_preferences": {
            "items": {
                "properties": {
                    "high_hp_preference": {
                        "type": "integer"
                    },
                    "low_hp_preference": {
                        "type": "integer"
                    },
                    "move_battle_style": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "high_hp_preference",
                    "low_hp_preference",
                    "move_battle_style"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "properties": {
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "pokeathlon_stat_changes": {
            "items": {
                "properties": {
                    "max_change": {
                        "type": "integer"
                    },
                    "pokeathlon_stat": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "max_change",
                    "pokeathlon_stat"
                ],
                "type": "object"
            },
            "type": "array"
        }
    },
    "required": [
        "decreased_stat",
        "hates_flavor",
        "id",
        "increased_stat",
        "likes_flavor",
        "move_battle_style_preferences",
        "name",
        "names",
        "pokeathlon_stat_changes"
    ],
    "type": "object"
}

=== Kirin92/ditto/api/v2/nature/10/index.json
{"name":"hasty","pokeathlon_stat_changes":[{"pokeathlon_stat":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokeathlon-stat\/1\/","name":"speed"},"max_change":2},{"pokeathlon_stat":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokeathlon-stat\/3\/","name":"skill"},"max_change":-2}],"names":[{"name":"\u305b\u3063\u304b\u3061","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/1\/","name":"ja"}},{"name":"\uc131\uae09","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/3\/","name":"ko"}},{"name":"Press\u00e9","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}},{"name":"Hastig","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/6\/","name":"de"}},{"name":"Activo","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/7\/","name":"es"}},{"name":"Lesta","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/8\/","name":"it"}},{"name":"Hasty","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}}],"hates_flavor":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/berry-flavor\/5\/","name":"sour"},"likes_flavor":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/berry-flavor\/3\/","name":"sweet"},"decreased_stat":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/stat\/3\/","name":"defense"},"move_battle_style_preferences":[{"high_hp_preference":58,"low_hp_preference":88,"move_battle_style":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move-battle-style\/1\/","name":"attack"}},{"high_hp_preference":37,"low_hp_preference":6,"move_battle_style":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move-battle-style\/2\/","name":"defense"}},{"high_hp_preference":5,"low_hp_preference":6,"move_battle_style":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move-battle-style\/3\/","name":"support"}}],"id":10,"increased_stat":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/stat\/6\/","name":"speed"}}

=== Kirin92/ditto/api/v2/nature/16/index.json
{"name":"jolly","pokeathlon_stat_changes":[{"pokeathlon_stat":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokeathlon-stat\/1\/","name":"speed"},"max_change":2},{"pokeathlon_stat":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/pokeathlon-stat\/5\/","name":"jump"},"max_change":-2}],"names":[{"name":"\u3088\u3046\u304d","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/1\/","name":"ja"}},{"name":"\uba85\ub791","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/3\/","name":"ko"}},{"name":"Jovial","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}},{"name":"Froh","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/6\/","name":"de"}},{"name":"Alegre","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/7\/","name":"es"}},{"name":"Allegra","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/8\/","name":"it"}},{"name":"Jolly","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}}],"hates_flavor":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/berry-flavor\/2\/","name":"dry"},"likes_flavor":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/berry-flavor\/3\/","name":"sweet"},"decreased_stat":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/stat\/4\/","name":"special-attack"},"move_battle_style_preferences":[{"high_hp_preference":35,"low_hp_preference":35,"move_battle_style":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move-battle-style\/1\/","name":"attack"}},{"high_hp_preference":5,"low_hp_preference":60,"move_battle_style":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move-battle-style\/2\/","name":"defense"}},{"high_hp_preference":60,"low_hp_preference":5,"move_battle_style":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move-battle-style\/3\/","name":"support"}}],"id":16,"increased_stat":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/stat\/6\/","name":"speed"}}
