=== Kirin92/ditto/data/schema/v2/move-ailment/-1/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "id": {
            "type": "integer"
        },
        "moves": {
            "items": {
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "url"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "properties": {
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        }
    },
    "required": [
        "id",
        "moves",
        "name",
        "names"
    ],
    "type": "object"
}

=== Kirin92/ditto/api/v2/move-ailment/1/index.json
{"moves":[{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/9\/","name":"thunder-punch"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/34\/","name":"body-slam"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/78\/","name":"stun-spore"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/84\/","name":"thunder-shock"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/85\/","name":"thunderbolt"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/86\/","name":"thunder-wave"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/87\/","name":"thunder"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/122\/","name":"lick"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/137\/","name":"glare"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/192\/","name":"zap-cannon"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/209\/","name":"spark"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/225\/","name":"dragon-breath"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/340\/","name":"bounce"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/344\/","name":"volt-tackle"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/395\/","name":"force-palm"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/422\/","name":"thunder-fang"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/435\/","name":"discharge"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/550\/","name":"bolt-strike"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/553\/","name":"freeze-shock"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/609\/","name":"nuzzle"}],"names":[{"name":"Paralysie","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}},{"name":"Paralysis","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}}],"id":1,"name":"paralysis"}

=== Kirin92/ditto/api/v2/move-ailment/9/index.json
{
    "id": 9,
    "moves": [
        {
            "name": "nightmare",
            "url": "http://127.0.0.1:8000/api/v2/move/171/"
        }
    ],
    "name": "nightmare",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "http://127.0.0.1:8000/api/v2/language/5/"
            },
            "name": "Cauchemar"
        },
        {
            "language": {
                "name": "en",
                "url": "http://127.0.0.1:8000/api/v2/language/9/"
            },
            "name": "Nightmare"
        }
    ]
}
