=== Kirin92/ditto/data/schema/v2/encounter-condition-value/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "condition": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        },
        "id": {
            "type": "integer"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "properties": {
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        }
    },
    "required": [
        "condition",
        "id",
        "name",
        "names"
    ],
    "type": "object"
}

=== Kirin92/ditto/data/api/v2/encounter-condition-value/19/index.json
{
    "condition": {
        "name": "season",
        "url": "http://localhost/api/v2/encounter-condition/6/"
    },
    "id": 19,
    "name": "season-autumn",
    "names": [
        {
            "language": {
                "name": "de",
                "url": "http://localhost/api/v2/language/6/"
            },
            "name": "Im Herbst"
        },
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "During Autumn"
        }
    ]
}
