=== Kirin92/ditto/data/schema/v2/encounter-condition/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "id": {
            "type": "integer"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "properties": {
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "values": {
            "items": {
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "url"
                ],
                "type": "object"
            },
            "type": "array"
        }
    },
    "required": [
        "id",
        "name",
        "names",
        "values"
    ],
    "type": "object"
}

=== Kirin92/ditto/api/v2/encounter-condition/5/index.json
{"names":[{"name":"Radio","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}},{"name":"Radio","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/6\/","name":"de"}},{"name":"Radio","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}}],"values":[{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-condition-value\/14\/","name":"radio-off"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-condition-value\/15\/","name":"radio-hoenn"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/encounter-condition-value\/16\/","name":"radio-sinnoh"}],"id":5,"name":"radio"}
