=== Kirin92/ditto/data/schema/v2/pokemon-form/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "form_name": {
            "type": "string"
        },
        "form_names": {
            "items": {
                "properties": {
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "form_order": {
            "type": "integer"
        },
        "id": {
            "type": "integer"
        },
        "is_battle_only": {
            "type": "boolean"
        },
        "is_default": {
            "type": "boolean"
        },
        "is_mega": {
            "type": "boolean"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "properties": {
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "order": {
            "type": "integer"
        },
        "pokemon": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        },
        "sprites": {
            "properties": {
                "back_default": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "back_shiny": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "front_default": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "front_shiny": {
                    "type": [
                        "null",
                        "string"
                    ]
                }
            },
            "required": [
                "back_default",
                "back_shiny",
                "front_default",
                "front_shiny"
            ],
            "type": "object"
        },
        "version_group": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        }
    },
    "required": [
        "form_name",
        "form_names",
        "form_order",
        "id",
        "is_battle_only",
        "is_default",
        "is_mega",
        "name",
        "names",
        "order",
        "pokemon",
        "sprites",
        "version_group"
    ],
    "type": "object"
}

=== Kirin92/ditto/data/api/v2/pokemon-form/231/index.json
{
    "form_name": "",
    "form_names": [],
    "form_order": 1,
    "id": 231,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "phanpy",
    "names": [],
    "order": 316,
    "pokemon": {
        "name": "phanpy",
        "url": "http://localhost/api/v2/pokemon/231/"
    },
    "sprites": {
        "back_default": "http://localhost/media/sprites/pokemon/back/231.png",
        "back_shiny": "http://localhost/media/sprites/pokemon/back/shiny/231.png",
        "front_default": "http://localhost/media/sprites/pokemon/231.png",
        "front_shiny": "http://localhost/media/sprites/pokemon/shiny/231.png"
    },
    "version_group": {
        "name": "gold-silver",
        "url": "http://localhost/api/v2/version-group/3/"
    }
}

=== Kirin92/ditto/data/api/v2/pokemon-form/703/index.json
{
    "form_name": "",
    "form_names": [],
    "form_order": 1,
    "id": 703,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "carbink",
    "names": [],
    "order": 866,
    "pokemon": {
        "name": "carbink",
        "url": "http://localhost/api/v2/pokemon/703/"
    },
    "sprites": {
        "back_default": null,
        "back_shiny": null,
        "front_default": "http://localhost/media/sprites/pokemon/703.png",
        "front_shiny": null
    },
    "version_group": {
        "name": "x-y",
        "url": "http://localhost/api/v2/version-group/15/"
    }
}

=== Kirin92/ditto/data/api/v2/pokemon-form/662/index.json
{
    "form_name": "",
    "form_names": [],
    "form_order": 1,
    "id": 662,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "fletchinder",
    "names": [],
    "order": 783,
    "pokemon": {
        "name": "fletchinder",
        "url": "http://localhost/api/v2/pokemon/662/"
    },
    "sprites": {
        "back_default": null,
        "back_shiny": null,
        "front_default": "http://localhost/media/sprites/pokemon/662.png",
        "front_shiny": null
    },
    "version_group": {
        "name": "x-y",
        "url": "http://localhost/api/v2/version-group/15/"
    }
}
