=== Kirin92/ditto/data/schema/v2/pokemon-form/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "form_name": {
            "type": "string"
        },
        "form_names": {
            "items": {
                "properties": {
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "form_order": {
            "type": "integer"
        },
        "id": {
            "type": "integer"
        },
        "is_battle_only": {
            "type": "boolean"
        },
        "is_default": {
            "type": "boolean"
        },
        "is_mega": {
            "type": "boolean"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "properties": {
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "order": {
            "type": "integer"
        },
        "pokemon": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        },
        "sprites": {
            "properties": {
                "back_default": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "back_shiny": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "front_default": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "front_shiny": {
                    "type": [
                        "null",
                        "string"
                    ]
                }
            },
            "required": [
                "back_default",
                "back_shiny",
                "front_default",
                "front_shiny"
            ],
            "type": "object"
        },
        "version_group": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        }
    },
    "required": [
        "form_name",
        "form_names",
        "form_order",
        "id",
        "is_battle_only",
        "is_default",
        "is_mega",
        "name",
        "names",
        "order",
        "pokemon",
        "sprites",
        "version_group"
    ],
    "type": "object"
}

=== Kirin92/ditto/data/api/v2/pokemon-form/41/index.json
{
    "form_name": "",
    "form_names": [],
    "form_order": 1,
    "id": 41,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "zubat",
    "names": [],
    "order": 57,
    "pokemon": {
        "name": "zubat",
        "url": "http://localhost/api/v2/pokemon/41/"
    },
    "sprites": {
        "back_default": "http://localhost/media/sprites/pokemon/back/41.png",
        "back_shiny": "http://localhost/media/sprites/pokemon/back/shiny/41.png",
        "front_default": "http://localhost/media/sprites/pokemon/41.png",
        "front_shiny": "http://localhost/media/sprites/pokemon/shiny/41.png"
    },
    "version_group": {
        "name": "red-blue",
        "url": "http://localhost/api/v2/version-group/1/"
    }
}

=== Kirin92/ditto/data/api/v2/pokemon-form/340/index.json
{
    "form_name": "",
    "form_names": [],
    "form_order": 1,
    "id": 340,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "whiscash",
    "names": [],
    "order": 435,
    "pokemon": {
        "name": "whiscash",
        "url": "http://localhost/api/v2/pokemon/340/"
    },
    "sprites": {
        "back_default": "http://localhost/media/sprites/pokemon/back/340.png",
        "back_shiny": "http://localhost/media/sprites/pokemon/back/shiny/340.png",
        "front_default": "http://localhost/media/sprites/pokemon/340.png",
        "front_shiny": "http://localhost/media/sprites/pokemon/shiny/340.png"
    },
    "version_group": {
        "name": "ruby-sapphire",
        "url": "http://localhost/api/v2/version-group/5/"
    }
}

=== Kirin92/ditto/data/api/v2/pokemon-form/709/index.json
{
    "form_name": "",
    "form_names": [],
    "form_order": 1,
    "id": 709,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "trevenant",
    "names": [],
    "order": 872,
    "pokemon": {
        "name": "trevenant",
        "url": "http://localhost/api/v2/pokemon/709/"
    },
    "sprites": {
        "back_default": null,
        "back_shiny": null,
        "front_default": "http://localhost/media/sprites/pokemon/709.png",
        "front_shiny": null
    },
    "version_group": {
        "name": "x-y",
        "url": "http://localhost/api/v2/version-group/15/"
    }
}

=== Kirin92/ditto/data/api/v2/pokemon-form/10125/index.json
{
    "form_name": "blade",
    "form_names": [
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "Blade Forme"
        },
        {
            "language": {
                "name": "it",
                "url": "http://localhost/api/v2/language/8/"
            },
            "name": "Forma Spada"
        },
        {
            "language": {
                "name": "es",
                "url": "http://localhost/api/v2/language/7/"
            },
            "name": "Forma Filo"
        },
        {
            "language": {
                "name": "de",
                "url": "http://localhost/api/v2/language/6/"
            },
            "name": "Klingenform"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "name": "Forme Assaut"
        },
        {
            "language": {
                "name": "ko",
                "url": "http://localhost/api/v2/language/3/"
            },
            "name": "\ube14\ub808\uc774\ub4dc\ud3fc"
        },
        {
            "language": {
                "name": "ja",
                "url": "http://localhost/api/v2/language/1/"
            },
            "name": "\u30d6\u30ec\u30fc\u30c9\u30d5\u30a9\u30eb\u30e0"
        }
    ],
    "form_order": 2,
    "id": 10125,
    "is_battle_only": true,
    "is_default": true,
    "is_mega": false,
    "name": "aegislash-blade",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "Blade Aegislash"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "name": "Exagide Assaut"
        }
    ],
    "order": 845,
    "pokemon": {
        "name": "aegislash-blade",
        "url": "http://localhost/api/v2/pokemon/10026/"
    },
    "sprites": {
        "back_default": null,
        "back_shiny": null,
        "front_default": "http://localhost/media/sprites/pokemon/681-blade.png",
        "front_shiny": null
    },
    "version_group": {
        "name": "x-y",
        "url": "http://localhost/api/v2/version-group/15/"
    }
}

=== Kirin92/ditto/data/api/v2/pokemon-form/10015/index.json
{
    "form_name": "p",
    "form_names": [
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "P"
        },
        {
            "language": {
                "name": "it",
                "url": "http://localhost/api/v2/language/8/"
            },
            "name": "P"
        },
        {
            "language": {
                "name": "es",
                "url": "http://localhost/api/v2/language/7/"
            },
            "name": "P"
        },
        {
            "language": {
                "name": "de",
                "url": "http://localhost/api/v2/language/6/"
            },
            "name": "P"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "name": "P"
        },
        {
            "language": {
                "name": "ko",
                "url": "http://localhost/api/v2/language/3/"
            },
            "name": "P"
        },
        {
            "language": {
                "name": "ja",
                "url": "http://localhost/api/v2/language/1/"
            },
            "name": "\uff30"
        }
    ],
    "form_order": 16,
    "id": 10015,
    "is_battle_only": false,
    "is_default": false,
    "is_mega": false,
    "name": "unown-p",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "Unown P"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "name": "Zarbi P"
        }
    ],
    "order": 271,
    "pokemon": {
        "name": "unown",
        "url": "http://localhost/api/v2/pokemon/201/"
    },
    "sprites": {
        "back_default": "http://localhost/media/sprites/pokemon/back/201-p.png",
        "back_shiny": "http://localhost/media/sprites/pokemon/back/shiny/201-p.png",
        "front_default": "http://localhost/media/sprites/pokemon/201-p.png",
        "front_shiny": "http://localhost/media/sprites/pokemon/shiny/201-p.png"
    },
    "version_group": {
        "name": "gold-silver",
        "url": "http://localhost/api/v2/version-group/3/"
    }
}

=== Kirin92/ditto/data/api/v2/pokemon-form/691/index.json
{
    "form_name": "",
    "form_names": [],
    "form_order": 1,
    "id": 691,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "dragalge",
    "names": [],
    "order": 855,
    "pokemon": {
        "name": "dragalge",
        "url": "http://localhost/api/v2/pokemon/691/"
    },
    "sprites": {
        "back_default": null,
        "back_shiny": null,
        "front_default": "http://localhost/media/sprites/pokemon/691.png",
        "front_shiny": null
    },
    "version_group": {
        "name": "x-y",
        "url": "http://localhost/api/v2/version-group/15/"
    }
}

=== Kirin92/ditto/data/api/v2/pokemon-form/10171/index.json
{
    "form_name": "mega",
    "form_names": [
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "Mega Audino"
        }
    ],
    "form_order": 2,
    "id": 10171,
    "is_battle_only": true,
    "is_default": true,
    "is_mega": true,
    "name": "audino-mega",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "Mega Audino"
        }
    ],
    "order": 636,
    "pokemon": {
        "name": "audino-mega",
        "url": "http://localhost/api/v2/pokemon/10069/"
    },
    "sprites": {
        "back_default": null,
        "back_shiny": null,
        "front_default": "http://localhost/media/sprites/pokemon/10069.png",
        "front_shiny": null
    },
    "version_group": {
        "name": "omega-ruby-alpha-sapphire",
        "url": "http://localhost/api/v2/version-group/16/"
    }
}

=== Kirin92/ditto/data/api/v2/pokemon-form/454/index.json
{
    "form_name": "",
    "form_names": [],
    "form_order": 1,
    "id": 454,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "toxicroak",
    "names": [],
    "order": 567,
    "pokemon": {
        "name": "toxicroak",
        "url": "http://localhost/api/v2/pokemon/454/"
    },
    "sprites": {
        "back_default": "http://localhost/media/sprites/pokemon/back/454.png",
        "back_shiny": "http://localhost/media/sprites/pokemon/back/shiny/454.png",
        "front_default": "http://localhost/media/sprites/pokemon/454.png",
        "front_shiny": "http://localhost/media/sprites/pokemon/shiny/454.png"
    },
    "version_group": {
        "name": "diamond-pearl",
        "url": "http://localhost/api/v2/version-group/8/"
    }
}
