=== Kirin92/ditto/data/schema/v2/machine/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "id": {
            "type": "integer"
        },
        "item": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        },
        "move": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        },
        "version_group": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        }
    },
    "required": [
        "id",
        "item",
        "move",
        "version_group"
    ],
    "type": "object"
}

=== Kirin92/ditto/data/api/v2/machine/530/index.json
{
    "id": 530,
    "item": {
        "name": "tm34",
        "url": "http://localhost/api/v2/item/338/"
    },
    "move": {
        "name": "bide",
        "url": "http://localhost/api/v2/move/117/"
    },
    "version_group": {
        "name": "yellow",
        "url": "http://localhost/api/v2/version-group/2/"
    }
}

=== Kirin92/ditto/data/api/v2/machine/254/index.json
{
    "id": 254,
    "item": {
        "name": "tm16",
        "url": "http://localhost/api/v2/item/320/"
    },
    "move": {
        "name": "light-screen",
        "url": "http://localhost/api/v2/move/113/"
    },
    "version_group": {
        "name": "black-2-white-2",
        "url": "http://localhost/api/v2/version-group/14/"
    }
}

=== Kirin92/ditto/data/api/v2/machine/676/index.json
{
    "id": 676,
    "item": {
        "name": "tm43",
        "url": "http://127.0.0.1:8000/api/v2/item/347/"
    },
    "move": {
        "name": "detect",
        "url": "http://127.0.0.1:8000/api/v2/move/197/"
    },
    "version_group": {
        "name": "crystal",
        "url": "http://127.0.0.1:8000/api/v2/version-group/4/"
    }
}

=== Kirin92/ditto/data/api/v2/machine/1067/index.json
{
    "id": 1067,
    "item": {
        "name": "tm78",
        "url": "http://localhost/api/v2/item/382/"
    },
    "move": {
        "name": "captivate",
        "url": "http://localhost/api/v2/move/445/"
    },
    "version_group": {
        "name": "diamond-pearl",
        "url": "http://localhost/api/v2/version-group/8/"
    }
}

=== Kirin92/ditto/data/api/v2/machine/659/index.json
{
    "id": 659,
    "item": {
        "name": "tm42",
        "url": "http://127.0.0.1:8000/api/v2/item/346/"
    },
    "move": {
        "name": "dream-eater",
        "url": "http://127.0.0.1:8000/api/v2/move/138/"
    },
    "version_group": {
        "name": "gold-silver",
        "url": "http://127.0.0.1:8000/api/v2/version-group/3/"
    }
}

=== Kirin92/ditto/data/api/v2/machine/1010/index.json
{
    "id": 1010,
    "item": {
        "name": "tm70",
        "url": "http://localhost/api/v2/item/374/"
    },
    "move": {
        "name": "aurora-veil",
        "url": "http://localhost/api/v2/move/694/"
    },
    "version_group": {
        "name": "sun-moon",
        "url": "http://localhost/api/v2/version-group/17/"
    }
}

=== Kirin92/ditto/data/api/v2/machine/717/index.json
{
    "id": 717,
    "item": {
        "name": "tm43",
        "url": "http://localhost/api/v2/item/347/"
    },
    "move": {
        "name": "detect",
        "url": "http://localhost/api/v2/move/197/"
    },
    "version_group": {
        "name": "gold-silver",
        "url": "http://localhost/api/v2/version-group/3/"
    }
}

=== Kirin92/ditto/api/v2/machine/345/index.json
{
    "id": 345,
    "item": {
        "name": "tm22",
        "url": "http://127.0.0.1:8000/api/v2/item/326/"
    },
    "move": {
        "name": "solar-beam",
        "url": "http://127.0.0.1:8000/api/v2/move/76/"
    },
    "version_group": {
        "name": "platinum",
        "url": "http://127.0.0.1:8000/api/v2/version-group/9/"
    }
}
