=== Kirin92/ditto/data/schema/v2/machine/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "id": {
            "type": "integer"
        },
        "item": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        },
        "move": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        },
        "version_group": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        }
    },
    "required": [
        "id",
        "item",
        "move",
        "version_group"
    ],
    "type": "object"
}

=== Kirin92/ditto/data/api/v2/machine/112/index.json
{
    "id": 112,
    "item": {
        "name": "tm07",
        "url": "http://localhost/api/v2/item/311/"
    },
    "move": {
        "name": "hail",
        "url": "http://localhost/api/v2/move/258/"
    },
    "version_group": {
        "name": "heartgold-soulsilver",
        "url": "http://localhost/api/v2/version-group/10/"
    }
}

=== Kirin92/ditto/data/api/v2/machine/1199/index.json
{
    "id": 1199,
    "item": {
        "name": "hm06",
        "url": "http://127.0.0.1:8000/api/v2/item/402/"
    },
    "move": {
        "name": "rock-smash",
        "url": "http://127.0.0.1:8000/api/v2/move/249/"
    },
    "version_group": {
        "name": "ruby-sapphire",
        "url": "http://127.0.0.1:8000/api/v2/version-group/5/"
    }
}

=== Kirin92/ditto/data/api/v2/machine/1175/index.json
{
    "id": 1175,
    "item": {
        "name": "tm91",
        "url": "http://localhost/api/v2/item/395/"
    },
    "move": {
        "name": "flash-cannon",
        "url": "http://localhost/api/v2/move/430/"
    },
    "version_group": {
        "name": "black-2-white-2",
        "url": "http://localhost/api/v2/version-group/14/"
    }
}

=== Kirin92/ditto/data/api/v2/machine/105/index.json
{
    "id": 105,
    "item": {
        "name": "tm07",
        "url": "http://localhost/api/v2/item/311/"
    },
    "move": {
        "name": "zap-cannon",
        "url": "http://localhost/api/v2/move/192/"
    },
    "version_group": {
        "name": "gold-silver",
        "url": "http://localhost/api/v2/version-group/3/"
    }
}

=== Kirin92/ditto/api/v2/machine/363/index.json
{
    "id": 363,
    "item": {
        "name": "tm23",
        "url": "http://127.0.0.1:8000/api/v2/item/327/"
    },
    "move": {
        "name": "smack-down",
        "url": "http://127.0.0.1:8000/api/v2/move/479/"
    },
    "version_group": {
        "name": "black-white",
        "url": "http://127.0.0.1:8000/api/v2/version-group/11/"
    }
}

=== Kirin92/ditto/data/api/v2/machine/111/index.json
{
    "id": 111,
    "item": {
        "name": "tm07",
        "url": "http://localhost/api/v2/item/311/"
    },
    "move": {
        "name": "hail",
        "url": "http://localhost/api/v2/move/258/"
    },
    "version_group": {
        "name": "x-y",
        "url": "http://localhost/api/v2/version-group/15/"
    }
}

=== Kirin92/ditto/api/v2/machine/1065/index.json
{
    "id": 1065,
    "item": {
        "name": "tm88",
        "url": "http://127.0.0.1:8000/api/v2/item/392/"
    },
    "move": {
        "name": "sleep-talk",
        "url": "http://127.0.0.1:8000/api/v2/move/214/"
    },
    "version_group": {
        "name": "x-y",
        "url": "http://127.0.0.1:8000/api/v2/version-group/15/"
    }
}

=== Kirin92/ditto/data/api/v2/machine/421/index.json
{
    "id": 421,
    "item": {
        "name": "tm27",
        "url": "http://127.0.0.1:8000/api/v2/item/331/"
    },
    "move": {
        "name": "return",
        "url": "http://127.0.0.1:8000/api/v2/move/216/"
    },
    "version_group": {
        "name": "ruby-sapphire",
        "url": "http://127.0.0.1:8000/api/v2/version-group/5/"
    }
}
