=== Kirin92/ditto/data/schema/v2/machine/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "id": {
            "type": "integer"
        },
        "item": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        },
        "move": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        },
        "version_group": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        }
    },
    "required": [
        "id",
        "item",
        "move",
        "version_group"
    ],
    "type": "object"
}

=== Kirin92/ditto/data/api/v2/machine/852/index.json
{
    "id": 852,
    "item": {
        "name": "tm58",
        "url": "http://localhost/api/v2/item/362/"
    },
    "move": {
        "name": "endure",
        "url": "http://localhost/api/v2/move/203/"
    },
    "version_group": {
        "name": "heartgold-soulsilver",
        "url": "http://localhost/api/v2/version-group/10/"
    }
}

=== Kirin92/ditto/data/api/v2/machine/617/index.json
{
    "id": 617,
    "item": {
        "name": "tm39",
        "url": "http://127.0.0.1:8000/api/v2/item/343/"
    },
    "move": {
        "name": "rock-tomb",
        "url": "http://127.0.0.1:8000/api/v2/move/317/"
    },
    "version_group": {
        "name": "platinum",
        "url": "http://127.0.0.1:8000/api/v2/version-group/9/"
    }
}

=== Kirin92/ditto/api/v2/machine/1168/index.json
{
    "id": 1168,
    "item": {
        "name": "hm04",
        "url": "http://127.0.0.1:8000/api/v2/item/400/"
    },
    "move": {
        "name": "strength",
        "url": "http://127.0.0.1:8000/api/v2/move/70/"
    },
    "version_group": {
        "name": "crystal",
        "url": "http://127.0.0.1:8000/api/v2/version-group/4/"
    }
}

=== Kirin92/ditto/data/api/v2/machine/21/index.json
{
    "id": 21,
    "item": {
        "name": "tm02",
        "url": "http://localhost/api/v2/item/306/"
    },
    "move": {
        "name": "headbutt",
        "url": "http://localhost/api/v2/move/29/"
    },
    "version_group": {
        "name": "crystal",
        "url": "http://localhost/api/v2/version-group/4/"
    }
}

=== Kirin92/ditto/data/api/v2/machine/979/index.json
{
    "id": 979,
    "item": {
        "name": "tm76",
        "url": "http://localhost/api/v2/item/380/"
    },
    "move": {
        "name": "struggle-bug",
        "url": "http://localhost/api/v2/move/522/"
    },
    "version_group": {
        "name": "black-white",
        "url": "http://localhost/api/v2/version-group/11/"
    }
}

=== Kirin92/ditto/data/api/v2/machine/1107/index.json
{
    "id": 1107,
    "item": {
        "name": "tm96",
        "url": "http://127.0.0.1:8000/api/v2/item/745/"
    },
    "move": {
        "name": "nature-power",
        "url": "http://127.0.0.1:8000/api/v2/move/267/"
    },
    "version_group": {
        "name": "x-y",
        "url": "http://127.0.0.1:8000/api/v2/version-group/15/"
    }
}

=== Kirin92/ditto/data/api/v2/machine/673/index.json
{
    "id": 673,
    "item": {
        "name": "tm43",
        "url": "http://127.0.0.1:8000/api/v2/item/347/"
    },
    "move": {
        "name": "sky-attack",
        "url": "http://127.0.0.1:8000/api/v2/move/143/"
    },
    "version_group": {
        "name": "red-blue",
        "url": "http://127.0.0.1:8000/api/v2/version-group/1/"
    }
}

=== Kirin92/ditto/api/v2/machine/1093/index.json
{
    "id": 1093,
    "item": {
        "name": "tm92",
        "url": "http://127.0.0.1:8000/api/v2/item/396/"
    },
    "move": {
        "name": "trick-room",
        "url": "http://127.0.0.1:8000/api/v2/move/433/"
    },
    "version_group": {
        "name": "x-y",
        "url": "http://127.0.0.1:8000/api/v2/version-group/15/"
    }
}
