=== Kirin92/ditto/data/schema/v2/super-contest-effect/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "appeal": {
            "type": "integer"
        },
        "flavor_text_entries": {
            "items": {
                "properties": {
                    "flavor_text": {
                        "type": "string"
                    },
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "flavor_text",
                    "language"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "id": {
            "type": "integer"
        },
        "moves": {
            "items": {
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "url"
                ],
                "type": "object"
            },
            "type": "array"
        }
    },
    "required": [
        "appeal",
        "flavor_text_entries",
        "id",
        "moves"
    ],
    "type": "object"
}

=== Kirin92/ditto/api/v2/super-contest-effect/21/index.json
{"moves":[{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/20\/","name":"bind"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/35\/","name":"wrap"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/73\/","name":"leech-seed"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/80\/","name":"petal-dance"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/83\/","name":"fire-spin"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/132\/","name":"constrict"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/174\/","name":"curse"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/250\/","name":"whirlpool"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/275\/","name":"ingrain"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/328\/","name":"sand-tomb"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/376\/","name":"trump-card"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/move\/387\/","name":"last-resort"}],"appeal":0,"flavor_text_entries":[{"flavor_text":"Earn a higher score the later the Pok\u00e9mon performs.","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}}],"id":21}
