=== Kirin92/ditto/data/schema/v2/location/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "areas": {
            "items": {
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "url"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "game_indices": {
            "items": {
                "properties": {
                    "game_index": {
                        "type": "integer"
                    },
                    "generation": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "game_index",
                    "generation"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "id": {
            "type": "integer"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "properties": {
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "region": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "url": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "name",
                        "url"
                    ],
                    "type": "object"
                }
            ]
        }
    },
    "required": [
        "areas",
        "game_indices",
        "id",
        "name",
        "names",
        "region"
    ],
    "type": "object"
}

=== Kirin92/ditto/data/api/v2/location/370/index.json
{
    "areas": [
        {
            "name": "unova-route-15-area",
            "url": "http://127.0.0.1:8000/api/v2/location-area/650/"
        }
    ],
    "game_indices": [
        {
            "game_index": 28,
            "generation": {
                "name": "generation-v",
                "url": "http://127.0.0.1:8000/api/v2/generation/5/"
            }
        },
        {
            "game_index": 102,
            "generation": {
                "name": "generation-v",
                "url": "http://127.0.0.1:8000/api/v2/generation/5/"
            }
        }
    ],
    "id": 370,
    "name": "unova-route-15",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://127.0.0.1:8000/api/v2/language/9/"
            },
            "name": "Route 15"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://127.0.0.1:8000/api/v2/language/5/"
            },
            "name": "Route 15"
        },
        {
            "language": {
                "name": "ja",
                "url": "http://127.0.0.1:8000/api/v2/language/1/"
            },
            "name": "\uff11\uff15\u756a\u9053\u8def"
        }
    ],
    "region": {
        "name": "unova",
        "url": "http://127.0.0.1:8000/api/v2/region/5/"
    }
}

=== Kirin92/ditto/api/v2/location/120/index.json
{"name":"kanto-route-4","region":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/region\/1\/","name":"kanto"},"game_indices":[{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/4\/","name":"generation-iv"},"game_index":152}],"names":[{"name":"Route 4","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"name":"Route 4","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}}],"id":120,"areas":[{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/location-area\/532\/","name":"kanto-route-4-area"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/location-area\/298\/","name":"kanto-route-4-area"}]}

=== Kirin92/ditto/data/api/v2/location/127/index.json
{
    "areas": [
        {
            "name": "johto-route-46-area",
            "url": "http://127.0.0.1:8000/api/v2/location-area/252/"
        }
    ],
    "game_indices": [
        {
            "game_index": 194,
            "generation": {
                "name": "generation-iv",
                "url": "http://127.0.0.1:8000/api/v2/generation/4/"
            }
        }
    ],
    "id": 127,
    "name": "johto-route-46",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://127.0.0.1:8000/api/v2/language/9/"
            },
            "name": "Route 46"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://127.0.0.1:8000/api/v2/language/5/"
            },
            "name": "Route 46"
        }
    ],
    "region": {
        "name": "johto",
        "url": "http://127.0.0.1:8000/api/v2/region/2/"
    }
}

=== Kirin92/ditto/api/v2/location/250/index.json
{"name":"cliff-edge-gate","region":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/region\/2\/","name":"johto"},"game_indices":[{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/4\/","name":"generation-iv"},"game_index":234}],"names":[{"name":"Cliff Edge Gate","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"name":"Portail Falaise","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}}],"id":250,"areas":[]}

=== Kirin92/ditto/data/api/v2/location/643/index.json
{
    "areas": [],
    "game_indices": [
        {
            "game_index": 86,
            "generation": {
                "name": "generation-vi",
                "url": "http://127.0.0.1:8000/api/v2/generation/6/"
            }
        }
    ],
    "id": 643,
    "name": "anistar-city",
    "names": [
        {
            "language": {
                "name": "ja-kanji",
                "url": "http://127.0.0.1:8000/api/v2/language/11/"
            },
            "name": "\u30d2\u30e3\u30c3\u30b3\u30af\u30b7\u30c6\u30a3"
        },
        {
            "language": {
                "name": "en",
                "url": "http://127.0.0.1:8000/api/v2/language/9/"
            },
            "name": "Anistar City"
        },
        {
            "language": {
                "name": "it",
                "url": "http://127.0.0.1:8000/api/v2/language/8/"
            },
            "name": "Fluxopoli"
        },
        {
            "language": {
                "name": "es",
                "url": "http://127.0.0.1:8000/api/v2/language/7/"
            },
            "name": "Ciudad Fluxus"
        },
        {
            "language": {
                "name": "de",
                "url": "http://127.0.0.1:8000/api/v2/language/6/"
            },
            "name": "Fluxia City"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://127.0.0.1:8000/api/v2/language/5/"
            },
            "name": "Flusselles"
        },
        {
            "language": {
                "name": "ko",
                "url": "http://127.0.0.1:8000/api/v2/language/3/"
            },
            "name": "\ud5a5\uc804\uc2dc\ud2f0"
        },
        {
            "language": {
                "name": "ja",
                "url": "http://127.0.0.1:8000/api/v2/language/1/"
            },
            "name": "\u30d2\u30e3\u30c3\u30b3\u30af\u30b7\u30c6\u30a3"
        }
    ],
    "region": {
        "name": "kalos",
        "url": "http://127.0.0.1:8000/api/v2/region/6/"
    }
}

=== Kirin92/ditto/api/v2/location/555/index.json
{"name":"cave-of-being","region":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/region\/5\/","name":"unova"},"game_indices":[{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/5\/","name":"generation-v"},"game_index":142}],"names":[{"name":"Cave of Being","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"name":"Caverne des Esprits","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}},{"name":"\u5fc3\u306e\u7a7a\u6d1e","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/1\/","name":"ja"}}],"id":555,"areas":[]}

=== Kirin92/ditto/api/v2/location/410/index.json
{"name":"marvelous-bridge","region":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/region\/5\/","name":"unova"},"game_indices":[{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/5\/","name":"generation-v"},"game_index":68},{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/5\/","name":"generation-v"},"game_index":92}],"names":[{"name":"Marvelous Bridge","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"name":"Pont de l'Inconnu","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}},{"name":"\u30ef\u30f3\u30c0\u30fc\u30d6\u30ea\u30c3\u30b8","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/1\/","name":"ja"}}],"id":410,"areas":[{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/location-area\/622\/","name":"marvelous-bridge-area"}]}
