=== Kirin92/ditto/data/schema/v2/location/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "areas": {
            "items": {
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "url"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "game_indices": {
            "items": {
                "properties": {
                    "game_index": {
                        "type": "integer"
                    },
                    "generation": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "game_index",
                    "generation"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "id": {
            "type": "integer"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "properties": {
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "region": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "url": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "name",
                        "url"
                    ],
                    "type": "object"
                }
            ]
        }
    },
    "required": [
        "areas",
        "game_indices",
        "id",
        "name",
        "names",
        "region"
    ],
    "type": "object"
}

=== Kirin92/ditto/api/v2/location/5/index.json
{"name":"sinnoh-pokemon-league","region":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/region\/4\/","name":"sinnoh"},"game_indices":[{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/4\/","name":"generation-iv"},"game_index":15}],"names":[{"name":"Pok\u00e9mon League","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"name":"Ligue Pok\u00e9mon","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}}],"id":5,"areas":[{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/location-area\/5\/","name":"sinnoh-pokemon-league-area"}]}

=== Kirin92/ditto/data/api/v2/location/579/index.json
{
    "areas": [],
    "game_indices": [],
    "id": 579,
    "name": "sealed-chamber",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "Sealed Chamber"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "name": "Sanctuaire"
        }
    ],
    "region": {
        "name": "hoenn",
        "url": "http://localhost/api/v2/region/3/"
    }
}

=== Kirin92/ditto/api/v2/location/139/index.json
{"name":"bell-tower","region":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/region\/2\/","name":"johto"},"game_indices":[{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/4\/","name":"generation-iv"},"game_index":205}],"names":[{"name":"Bell Tower","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"name":"Tour Carillon","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}}],"id":139,"areas":[{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/location-area\/214\/","name":"bell-tower-2f"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/location-area\/215\/","name":"bell-tower-3f"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/location-area\/216\/","name":"bell-tower-4f"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/location-area\/217\/","name":"bell-tower-5f"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/location-area\/218\/","name":"bell-tower-6f"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/location-area\/219\/","name":"bell-tower-7f"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/location-area\/220\/","name":"bell-tower-8f"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/location-area\/221\/","name":"bell-tower-9f"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/location-area\/268\/","name":"bell-tower-10f"}]}

=== Kirin92/ditto/data/api/v2/location/466/index.json
{
    "areas": [
        {
            "name": "hoenn-route-118-area",
            "url": "http://localhost/api/v2/location-area/410/"
        }
    ],
    "game_indices": [],
    "id": 466,
    "name": "hoenn-route-118",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "Route 118"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "name": "Route 118"
        }
    ],
    "region": {
        "name": "hoenn",
        "url": "http://localhost/api/v2/region/3/"
    }
}

=== Kirin92/ditto/api/v2/location/439/index.json
{"name":"jagged-pass","region":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/region\/3\/","name":"hoenn"},"game_indices":[],"names":[{"name":"Jagged Pass","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"name":"Sentier Sinuroc","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}}],"id":439,"areas":[{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/location-area\/366\/","name":"jagged-pass-area"}]}

=== Kirin92/ditto/data/api/v2/location/112/index.json
{
    "areas": [
        {
            "name": "johto-route-32-area",
            "url": "http://localhost/api/v2/location-area/192/"
        }
    ],
    "game_indices": [
        {
            "game_index": 180,
            "generation": {
                "name": "generation-iv",
                "url": "http://localhost/api/v2/generation/4/"
            }
        }
    ],
    "id": 112,
    "name": "johto-route-32",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "Route 32"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "name": "Route 32"
        }
    ],
    "region": {
        "name": "johto",
        "url": "http://localhost/api/v2/region/2/"
    }
}

=== Kirin92/ditto/data/api/v2/location/458/index.json
{
    "areas": [
        {
            "name": "hoenn-route-110-area",
            "url": "http://127.0.0.1:8000/api/v2/location-area/402/"
        }
    ],
    "game_indices": [],
    "id": 458,
    "name": "hoenn-route-110",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://127.0.0.1:8000/api/v2/language/9/"
            },
            "name": "Route 110"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://127.0.0.1:8000/api/v2/language/5/"
            },
            "name": "Route 110"
        }
    ],
    "region": {
        "name": "hoenn",
        "url": "http://127.0.0.1:8000/api/v2/region/3/"
    }
}

=== Kirin92/ditto/data/api/v2/location/1/index.json
{
    "areas": [
        {
            "name": "canalave-city-area",
            "url": "http://127.0.0.1:8000/api/v2/location-area/1/"
        }
    ],
    "game_indices": [
        {
            "game_index": 7,
            "generation": {
                "name": "generation-iv",
                "url": "http://127.0.0.1:8000/api/v2/generation/4/"
            }
        }
    ],
    "id": 1,
    "name": "canalave-city",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://127.0.0.1:8000/api/v2/language/9/"
            },
            "name": "Canalave City"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://127.0.0.1:8000/api/v2/language/5/"
            },
            "name": "Joliberges"
        }
    ],
    "region": {
        "name": "sinnoh",
        "url": "http://127.0.0.1:8000/api/v2/region/4/"
    }
}
