=== Kirin92/ditto/data/schema/v2/location/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "areas": {
            "items": {
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "url"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "game_indices": {
            "items": {
                "properties": {
                    "game_index": {
                        "type": "integer"
                    },
                    "generation": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "game_index",
                    "generation"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "id": {
            "type": "integer"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "properties": {
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "region": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "url": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "name",
                        "url"
                    ],
                    "type": "object"
                }
            ]
        }
    },
    "required": [
        "areas",
        "game_indices",
        "id",
        "name",
        "names",
        "region"
    ],
    "type": "object"
}

=== Kirin92/ditto/data/api/v2/location/581/index.json
{
    "areas": [],
    "game_indices": [],
    "id": 581,
    "name": "island-cave",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "Island Cave"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "name": "Grotte Island"
        }
    ],
    "region": {
        "name": "hoenn",
        "url": "http://localhost/api/v2/region/3/"
    }
}

=== Kirin92/ditto/data/api/v2/location/491/index.json
{
    "areas": [
        {
            "name": "monean-chamber-area",
            "url": "http://localhost/api/v2/location-area/450/"
        }
    ],
    "game_indices": [],
    "id": 491,
    "name": "monean-chamber",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "Monean Chamber"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "name": "Chambre Anemune"
        }
    ],
    "region": {
        "name": "kanto",
        "url": "http://localhost/api/v2/region/1/"
    }
}

=== Kirin92/ditto/api/v2/location/241/index.json
{"name":"pokeathlon-dome","region":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/region\/2\/","name":"johto"},"game_indices":[{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/4\/","name":"generation-iv"},"game_index":225}],"names":[{"name":"Pok\u00e9athlon Dome","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"name":"D\u00f4me Pok\u00e9athlon","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}}],"id":241,"areas":[]}

=== Kirin92/ditto/api/v2/location/391/index.json
{"name":"musical-theater","region":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/region\/5\/","name":"unova"},"game_indices":[{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/5\/","name":"generation-v"},"game_index":49}],"names":[{"name":"Musical Theater","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"name":"Music-Hall","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}},{"name":"\u30df\u30e5\u30fc\u30b8\u30ab\u30eb\u30db\u30fc\u30eb","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/1\/","name":"ja"}}],"id":391,"areas":[]}

=== Kirin92/ditto/api/v2/location/483/index.json
{
    "areas": [
        {
            "name": "hoenn-safari-zone-nwmach-bike-area",
            "url": "http://127.0.0.1:8000/api/v2/location-area/429/"
        },
        {
            "name": "hoenn-safari-zone-neacro-bike-area",
            "url": "http://127.0.0.1:8000/api/v2/location-area/430/"
        },
        {
            "name": "hoenn-safari-zone-sw",
            "url": "http://127.0.0.1:8000/api/v2/location-area/431/"
        },
        {
            "name": "hoenn-safari-zone-se",
            "url": "http://127.0.0.1:8000/api/v2/location-area/432/"
        },
        {
            "name": "hoenn-safari-zone-expansion-south",
            "url": "http://127.0.0.1:8000/api/v2/location-area/435/"
        },
        {
            "name": "hoenn-safari-zone-expansion-north",
            "url": "http://127.0.0.1:8000/api/v2/location-area/436/"
        }
    ],
    "game_indices": [],
    "id": 483,
    "name": "hoenn-safari-zone",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://127.0.0.1:8000/api/v2/language/9/"
            },
            "name": "Safari Zone"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://127.0.0.1:8000/api/v2/language/5/"
            },
            "name": "Parc Safari"
        }
    ],
    "region": {
        "name": "hoenn",
        "url": "http://127.0.0.1:8000/api/v2/region/3/"
    }
}

=== Kirin92/ditto/api/v2/location/208/index.json
{"name":"sunyshore-market","region":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/region\/4\/","name":"sinnoh"},"game_indices":[{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/4\/","name":"generation-iv"},"game_index":105}],"names":[{"name":"Sunyshore Market","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"name":"March\u00e9 Rivamar","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}}],"id":208,"areas":[]}

=== Kirin92/ditto/api/v2/location/341/index.json
{"name":"concert-event","region":null,"game_indices":[{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/4\/","name":"generation-iv"},"game_index":3076}],"names":[{"name":"Concert Event","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"name":"Ev\u00e9nem. Concert","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}}],"id":341,"areas":[]}

=== Kirin92/ditto/api/v2/location/243/index.json
{
    "areas": [],
    "game_indices": [
        {
            "game_index": 227,
            "generation": {
                "name": "generation-iv",
                "url": "http://127.0.0.1:8000/api/v2/generation/4/"
            }
        }
    ],
    "id": 243,
    "name": "safari-zone-gate",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://127.0.0.1:8000/api/v2/language/9/"
            },
            "name": "Safari Zone Gate"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://127.0.0.1:8000/api/v2/language/5/"
            },
            "name": "Portail Safari"
        }
    ],
    "region": {
        "name": "johto",
        "url": "http://127.0.0.1:8000/api/v2/region/2/"
    }
}
