=== Kirin92/ditto/data/schema/v2/item/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "attributes": {
            "items": {
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "url"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "baby_trigger_for": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "properties": {
                        "url": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "url"
                    ],
                    "type": "object"
                }
            ]
        },
        "category": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        },
        "cost": {
            "type": "integer"
        },
        "effect_entries": {
            "items": {
                "properties": {
                    "effect": {
                        "type": "string"
                    },
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "short_effect": {
                        "type": "string"
                    }
                },
                "required": [
                    "effect",
                    "language",
                    "short_effect"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "flavor_text_entries": {
            "items": {
                "properties": {
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "text": {
                        "type": "string"
                    },
                    "version_group": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "language",
                    "text",
                    "version_group"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "fling_effect": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "url": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "name",
                        "url"
                    ],
                    "type": "object"
                }
            ]
        },
        "fling_power": {
            "type": [
                "integer",
                "null"
            ]
        },
        "game_indices": {
            "items": {
                "properties": {
                    "game_index": {
                        "type": "integer"
                    },
                    "generation": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "game_index",
                    "generation"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "held_by_pokemon": {
            "items": {
                "properties": {
                    "pokemon": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "version_details": {
                        "items": {
                            "properties": {
                                "rarity": {
                                    "type": "integer"
                                },
                                "version": {
                                    "properties": {
                                        "name": {
                                            "type": "string"
                                        },
                                        "url": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "name",
                                        "url"
                                    ],
                                    "type": "object"
                                }
                            },
                            "required": [
                                "rarity",
                                "version"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    }
                },
                "required": [
                    "pokemon",
                    "version_details"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "id": {
            "type": "integer"
        },
        "machines": {
            "items": {
                "properties": {
                    "machine": {
                        "properties": {
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "url"
                        ],
                        "type": "object"
                    },
                    "version_group": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "machine",
                    "version_group"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "properties": {
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "sprites": {
            "properties": {
                "default": {
                    "type": "string"
                }
            },
            "required": [
                "default"
            ],
            "type": "object"
        }
    },
    "required": [
        "attributes",
        "baby_trigger_for",
        "category",
        "cost",
        "effect_entries",
        "flavor_text_entries",
        "fling_effect",
        "fling_power",
        "game_indices",
        "held_by_pokemon",
        "id",
        "machines",
        "name",
        "names",
        "sprites"
    ],
    "type": "object"
}

=== Kirin92/ditto/api/v2/item/685/index.json
{"category":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/item-category\/26\/","name":"vitamins"},"name":"ability-capsule","fling_effect":null,"effect_entries":[],"held_by_pokemon":[],"sprites":{"default":"http:\/\/127.0.0.1:8000\/media\/sprites\/items\/ability-capsule.png"},"game_indices":[{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/6\/","name":"generation-vi"},"game_index":645}],"baby_trigger_for":null,"cost":0,"names":[{"name":"Ability Capsule","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"name":"Capsula abilit\u00e0","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/8\/","name":"it"}},{"name":"C\u00e1ps. Habilidad","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/7\/","name":"es"}},{"name":"F\u00e4higk.-Kapsel","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/6\/","name":"de"}},{"name":"Pilule Talent","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}},{"name":"\ud2b9\uc131\ucea1\uc290","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/3\/","name":"ko"}},{"name":"\u3068\u304f\u305b\u3044\u30ab\u30d7\u30bb\u30eb","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/1\/","name":"ja"}}],"attributes":[],"flavor_text_entries":[{"text":"\uff12\u7a2e\u985e\u306e\u3000\u7279\u6027\u3092\u3000\u6301\u3064\n\u30dd\u30b1\u30e2\u30f3\u306b\u3000\u4f7f\u3046\u3068\u3000\u4eca\u3068\u306f\u9055\u3046\n\u7279\u6027\u306b\u3000\u5909\u3048\u3089\u308c\u308b\u3000\u30ab\u30d7\u30bb\u30eb\u3002","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/11\/","name":"ja-kanji"}},{"text":"A capsule that allows a Pok\u00e9mon with\ntwo Abilities to switch between these\nAbilities when it is used.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"Se usata su un Pok\u00e9mon che ha due abilit\u00e0,\nquesta capsula permette di cambiare quella\nattiva.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/8\/","name":"it"}},{"text":"Una de las misteriosas Megapiedras. Permite\nmegaevolucionar a Blaziken en combate.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/7\/","name":"es"}},{"text":"Bei Anwendung auf ein Pok\u00e9mon, das zwei\nverschiedene F\u00e4higkeiten haben kann, wird seine\naktuelle F\u00e4higkeit mit der anderen ausgewechselt.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/6\/","name":"de"}},{"text":"Une capsule permettant \u00e0 un Pok\u00e9mon pouvant\navoir deux talents de changer de l\u2019un \u00e0 l\u2019autre.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}},{"text":"2\uc885\ub958\uc758 \ud2b9\uc131\uc744 \uac00\uc9c4\n\ud3ec\ucf13\ubaac\uc5d0\uac8c \uc0ac\uc6a9\ud558\uba74 \uc9c0\uae08\uacfc\ub294 \ub2e4\ub978\n\ud2b9\uc131\uc73c\ub85c \ubc14\uafc0 \uc218 \uc788\ub294 \ucea1\uc290.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/3\/","name":"ko"}},{"text":"\uff12\u3057\u3085\u308b\u3044\u306e\u3000\u3068\u304f\u305b\u3044\u3092\u3000\u3082\u3064\n\u30dd\u30b1\u30e2\u30f3\u306b\u3000\u3064\u304b\u3046\u3068\u3000\u3044\u307e\u3068\u306f\u3061\u304c\u3046\n\u3068\u304f\u305b\u3044\u306b\u3000\u304b\u3048\u3089\u308c\u308b\u3000\u30ab\u30d7\u30bb\u30eb\u3002","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/1\/","name":"ja"}}],"id":685,"machines":[],"fling_power":null}

=== Kirin92/ditto/api/v2/item/200/index.json
{"category":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/item-category\/16\/","name":"training"},"name":"amulet-coin","fling_effect":null,"effect_entries":[{"short_effect":"Held: Doubles the money earned from a battle. Does not stack with Luck Incense.","effect":"Held\n:   If the holder participated in a trainer battle, the trainer earns twice the usual prize money.  This effect applies even if the holder fainted.\n\n    This effect does not stack with any other similar effect.","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}}],"held_by_pokemon":[],"sprites":{"default":"http:\/\/127.0.0.1:8000\/media\/sprites\/items\/amulet-coin.png"},"game_indices":[{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/6\/","name":"generation-vi"},"game_index":223},{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/5\/","name":"generation-v"},"game_index":223},{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/4\/","name":"generation-iv"},"game_index":223},{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/3\/","name":"generation-iii"},"game_index":189}],"baby_trigger_for":null,"cost":100,"names":[{"name":"Amulet Coin","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"name":"Monetamuleto","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/8\/","name":"it"}},{"name":"Moneda Amuleto","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/7\/","name":"es"}},{"name":"M\u00fcnzamulett","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/6\/","name":"de"}},{"name":"Pi\u00e8ce Rune","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}},{"name":"\ubd80\uc801\uae08\ud654","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/3\/","name":"ko"}},{"name":"\u304a\u307e\u3082\u308a\u3053\u3070\u3093","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/1\/","name":"ja"}}],"attributes":[{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/item-attribute\/5\/","name":"holdable"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/item-attribute\/7\/","name":"holdable-active"}],"flavor_text_entries":[{"text":"\u6301\u305f\u305b\u305f\u3000\u30dd\u30b1\u30e2\u30f3\u304c\u3000\uff11\u5ea6\u3067\u3082\n\u6226\u95d8\u306b\u3000\u9854\u3092\u3000\u3060\u3059\u3068\n\u304a\u91d1\u304c\u3000\uff12\u500d\u3000\u3082\u3089\u3048\u308b\u3002","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/11\/","name":"ja-kanji"}},{"text":"An item to be held by a Pok\u00e9mon.\nIt doubles any prize money received\nif the holding Pok\u00e9mon joins a battle.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"Strumento da dare a un Pok\u00e9mon.\nSe chi ce l\u2019ha partecipa alla lotta, i guadagni\nraddoppiano.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/8\/","name":"it"}},{"text":"Debe llevarlas un Pok\u00e9mon. Fortalecen los\nmovimientos de tipo Siniestro.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/7\/","name":"es"}},{"text":"Ein Item, das von einem Pok\u00e9mon getragen wird\nund das doppeltes Preisgeld bringt, wenn der\nTr\u00e4ger am Kampf teilnimmt.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/6\/","name":"de"}},{"text":"Objet \u00e0 tenir. Double l\u2019argent gagn\u00e9 si le porteur\nse joint au combat.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}},{"text":"\uc9c0\ub2c8\uac8c \ud55c \ud3ec\ucf13\ubaac\uc774\n\ud55c \ubc88\uc774\ub77c\ub3c4 \ubc30\ud2c0\uc5d0 \ub098\uac00\uba74\n\ub3c8\uc744 2\ubc30\ub85c \ubc1b\uc744 \uc218 \uc788\ub2e4.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/3\/","name":"ko"}},{"text":"\u3082\u305f\u305b\u305f\u3000\u30dd\u30b1\u30e2\u30f3\u304c\u3000\u3044\u3061\u3069\u3067\u3082\n\u305b\u3093\u3068\u3046\u306b\u3000\u304b\u304a\u3092\u3000\u3060\u3059\u3068\n\u304a\u304b\u306d\u304c\u3000\uff12\u3070\u3044\u3000\u3082\u3089\u3048\u308b\u3002","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/1\/","name":"ja"}},{"text":"An item to be held by a Pok\u00e9mon.\nIt doubles a battle\u2019s prize money if\nthe holding Pok\u00e9mon joins in.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/14\/","name":"black-2-white-2"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"An item to be held by a Pok\u00e9mon.\nIt doubles a battle\u2019s prize money if\nthe holding Pok\u00e9mon joins in.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/11\/","name":"black-white"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"Objet \u00e0 tenir. Double l\u2019argent gagn\u00e9\nsi le porteur se joint au combat.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/11\/","name":"black-white"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}},{"text":"An item to be held by a Pok\u00e9mon.\nIt doubles a battle\u2019s prize money if\nthe holding Pok\u00e9mon joins in.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/10\/","name":"heartgold-soulsilver"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"An item to be held by a Pok\u00e9mon.\nIt doubles a battle\u2019s prize money if\nthe holding Pok\u00e9mon joins in.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/9\/","name":"platinum"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"An item to be held by a Pok\u00e9mon.\nIt doubles a battle\u2019s prize money if\nthe holding Pok\u00e9mon joins in.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/8\/","name":"diamond-pearl"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"An item to be held by a POK\u00e9MON.\nIt doubles the battle money if the\nholding POK\u00e9MON takes part.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/7\/","name":"firered-leafgreen"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"Doubles money in\nbattle if the\nholder takes part.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/6\/","name":"emerald"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"Doubles money in\nbattle if the holder\ntakes part.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/5\/","name":"ruby-sapphire"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}}],"id":200,"machines":[],"fling_power":30}

=== Kirin92/ditto/api/v2/item/482/index.json
{"category":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/item-category\/22\/","name":"plot-advancement"},"name":"rainbow-wing","fling_effect":null,"effect_entries":[{"short_effect":"Summons Ho-Oh at the top of the Bell Tower.","effect":"Causes ho oh to appear at the top of bell tower.","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}}],"held_by_pokemon":[],"sprites":{"default":"http:\/\/127.0.0.1:8000\/media\/sprites\/items\/rainbow-wing.png"},"game_indices":[{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/6\/","name":"generation-vi"},"game_index":483},{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/5\/","name":"generation-v"},"game_index":483},{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/4\/","name":"generation-iv"},"game_index":483}],"baby_trigger_for":null,"cost":0,"names":[{"name":"Rainbow Wing","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"name":"Ala d'Iride","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/8\/","name":"it"}},{"name":"Ala Arco\u00edris","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/7\/","name":"es"}},{"name":"Buntschwinge","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/6\/","name":"de"}},{"name":"Arcenci'Aile","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}},{"name":"\ubb34\uc9c0\uac2f\ube5b\ub0a0\uac1c","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/3\/","name":"ko"}},{"name":"\u306b\u3058\u3044\u308d\u306e\u306f\u306d","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/1\/","name":"ja"}}],"attributes":[],"flavor_text_entries":[{"text":"\u306b\u3058\u3044\u308d\u306b\u3000\u3072\u304b\u308a\u3000\u304b\u304c\u3084\u304f\n\u4e0d\u601d\u8b70\u306a\u3000\u306f\u306d\u3002\n","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/11\/","name":"ja-kanji"}},{"text":"A mystical rainbow feather\nthat sparkles.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"Piuma magica dai mille colori.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/8\/","name":"it"}},{"text":"Lector con el que se pueden escuchar aquellas\ncanciones tan nost\u00e1lgicas. Se cambia con un solo\ninterruptor.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/7\/","name":"es"}},{"text":"Eine mystische Feder, die von einem\nregenbogenfarbenen Leuchten erf\u00fcllt ist.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/6\/","name":"de"}},{"text":"Une \u00e9trange plume qui brille d\u2019un \u00e9clat\narc-en-ciel.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}},{"text":"\ubb34\uc9c0\uac2f\ube5b\uc73c\ub85c \ube5b\ub098\ub294\n\uc774\uc0c1\ud55c \ub0a0\uac1c.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/3\/","name":"ko"}},{"text":"\u306b\u3058\u3044\u308d\u306b\u3000\u3072\u304b\u308a\u3000\u304b\u304c\u3084\u304f\n\u3075\u3057\u304e\u306a\u3000\u306f\u306d\u3002\n","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/1\/","name":"ja"}},{"text":"A mystical rainbow feather\nthat sparkles.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/14\/","name":"black-2-white-2"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"A mystical rainbow feather\nthat sparkles.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/11\/","name":"black-white"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"Une \u00e9trange plume qui brille\nd\u2019un \u00e9clat arc-en-ciel.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/11\/","name":"black-white"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}},{"text":"A mystical, rainbow feather\nthat sparkles.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/10\/","name":"heartgold-soulsilver"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}}],"id":482,"machines":[],"fling_power":null}
