=== Kirin92/ditto/data/schema/v2/item/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "attributes": {
            "items": {
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "url"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "baby_trigger_for": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "properties": {
                        "url": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "url"
                    ],
                    "type": "object"
                }
            ]
        },
        "category": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        },
        "cost": {
            "type": "integer"
        },
        "effect_entries": {
            "items": {
                "properties": {
                    "effect": {
                        "type": "string"
                    },
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "short_effect": {
                        "type": "string"
                    }
                },
                "required": [
                    "effect",
                    "language",
                    "short_effect"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "flavor_text_entries": {
            "items": {
                "properties": {
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "text": {
                        "type": "string"
                    },
                    "version_group": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "language",
                    "text",
                    "version_group"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "fling_effect": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "url": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "name",
                        "url"
                    ],
                    "type": "object"
                }
            ]
        },
        "fling_power": {
            "type": [
                "integer",
                "null"
            ]
        },
        "game_indices": {
            "items": {
                "properties": {
                    "game_index": {
                        "type": "integer"
                    },
                    "generation": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "game_index",
                    "generation"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "held_by_pokemon": {
            "items": {
                "properties": {
                    "pokemon": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "version_details": {
                        "items": {
                            "properties": {
                                "rarity": {
                                    "type": "integer"
                                },
                                "version": {
                                    "properties": {
                                        "name": {
                                            "type": "string"
                                        },
                                        "url": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "name",
                                        "url"
                                    ],
                                    "type": "object"
                                }
                            },
                            "required": [
                                "rarity",
                                "version"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    }
                },
                "required": [
                    "pokemon",
                    "version_details"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "id": {
            "type": "integer"
        },
        "machines": {
            "items": {
                "properties": {
                    "machine": {
                        "properties": {
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "url"
                        ],
                        "type": "object"
                    },
                    "version_group": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "machine",
                    "version_group"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "properties": {
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "sprites": {
            "properties": {
                "default": {
                    "type": "string"
                }
            },
            "required": [
                "default"
            ],
            "type": "object"
        }
    },
    "required": [
        "attributes",
        "baby_trigger_for",
        "category",
        "cost",
        "effect_entries",
        "flavor_text_entries",
        "fling_effect",
        "fling_power",
        "game_indices",
        "held_by_pokemon",
        "id",
        "machines",
        "name",
        "names",
        "sprites"
    ],
    "type": "object"
}

=== Kirin92/ditto/api/v2/item/60/index.json
{"category":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/item-category\/1\/","name":"stat-boosts"},"name":"x-accuracy","fling_effect":null,"effect_entries":[{"short_effect":"Raises accuracy by one stage in battle.  Raises happiness.","effect":"Used on a party Pok\u00e9mon in battle\n:   Raises the target's accuracy by one stage.  Increases happiness by 1\/1\/0.","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}}],"held_by_pokemon":[],"sprites":{"default":"http:\/\/127.0.0.1:8000\/media\/sprites\/items\/x-accuracy.png"},"game_indices":[{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/6\/","name":"generation-vi"},"game_index":60},{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/5\/","name":"generation-v"},"game_index":60},{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/4\/","name":"generation-iv"},"game_index":60},{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/3\/","name":"generation-iii"},"game_index":78}],"baby_trigger_for":null,"cost":950,"names":[{"name":"X Accuracy","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"name":"Precisione X","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/8\/","name":"it"}},{"name":"Precisi\u00f3n X","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/7\/","name":"es"}},{"name":"X-Treffer","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/6\/","name":"de"}},{"name":"Pr\u00e9cision +","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}},{"name":"\uc798-\ub9de\ud788\uae30","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/3\/","name":"ko"}},{"name":"\u30e8\u30af\u30a2\u30bf\u30fc\u30eb","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/1\/","name":"ja"}}],"attributes":[{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/item-attribute\/5\/","name":"holdable"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/item-attribute\/4\/","name":"usable-in-battle"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/item-attribute\/2\/","name":"consumable"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/item-attribute\/1\/","name":"countable"}],"flavor_text_entries":[{"text":"\u6226\u95d8\u4e2d\u306e\u3000\u30dd\u30b1\u30e2\u30f3\u306e\n\u547d\u4e2d\u3092\u3000\u3042\u3052\u308b\u3000\u9053\u5177\u3002\n\u3072\u3063\u3053\u3081\u308b\u3068\u3000\u5143\u306b\u3000\u623b\u308b\u3002","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/11\/","name":"ja-kanji"}},{"text":"An item that boosts the accuracy of\na Pok\u00e9mon during a battle. It wears\noff once the Pok\u00e9mon is withdrawn.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"Aumenta la precisione di un Pok\u00e9mon in una\nlotta. L\u2019effetto svanisce se il Pok\u00e9mon\n\u00e8 sostituito.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/8\/","name":"it"}},{"text":"Aumenta la Precisi\u00f3n de los ataques en combate.\nAl cambiar de Pok\u00e9mon, el efecto desaparece.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/7\/","name":"es"}},{"text":"Hebt die Genauigkeit eines Pok\u00e9mon im Kampf.\nDie Wirkung wird mit dem Austausch des\nPok\u00e9mon beendet.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/6\/","name":"de"}},{"text":"Augmente la Pr\u00e9cision pendant un combat.\nL\u2019effet dispara\u00eet si le Pok\u00e9mon se retire.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}},{"text":"\ubc30\ud2c0 \uc911\uc778 \ud3ec\ucf13\ubaac\uc758 \uba85\uc911\ub960\uc744 \uc62c\ub9ac\ub294\n\ub3c4\uad6c. \ud3ec\ucf13\ubaac\uc744 \ubcfc\uc5d0 \ub123\uc5b4\ubc84\ub9ac\uba74\n\uc6d0\ub798\ub300\ub85c \ub418\ub3cc\uc544\uac04\ub2e4.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/3\/","name":"ko"}},{"text":"\u305b\u3093\u3068\u3046\u3061\u3085\u3046\u306e\u3000\u30dd\u30b1\u30e2\u30f3\u306e\n\u3081\u3044\u3061\u3085\u3046\u3092\u3000\u3042\u3052\u308b\u3000\u3069\u3046\u3050\u3002\n\u3072\u3063\u3053\u3081\u308b\u3068\u3000\u3082\u3068\u306b\u3000\u3082\u3069\u308b\u3002","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/1\/","name":"ja"}},{"text":"An item that raises the accuracy\nof a Pok\u00e9mon in battle. It wears off if\nthe Pok\u00e9mon is withdrawn.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/14\/","name":"black-2-white-2"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"An item that raises the accuracy\nof a Pok\u00e9mon in battle. It wears off if\nthe Pok\u00e9mon is withdrawn.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/11\/","name":"black-white"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"Monte la Pr\u00e9cision pendant un combat.\nL\u2019effet s\u2019estompe si le Pok\u00e9mon se\nretire.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/11\/","name":"black-white"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}},{"text":"An item that raises the accuracy\nof a Pok\u00e9mon in battle. It wears off if\nthe Pok\u00e9mon is withdrawn.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/10\/","name":"heartgold-soulsilver"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"An item that raises the accuracy\nof a Pok\u00e9mon in battle. It wears off if\nthe Pok\u00e9mon is withdrawn.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/9\/","name":"platinum"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"An item that raises the accuracy\nof a Pok\u00e9mon in battle. It wears off if\nthe Pok\u00e9mon is withdrawn.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/8\/","name":"diamond-pearl"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"Raises the accuracy stat of\nPOK\u00e9MON in battle. Wears off if the\nPOK\u00e9MON is withdrawn.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/7\/","name":"firered-leafgreen"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"Raises accuracy\nof attack moves\nduring one battle.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/6\/","name":"emerald"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"Raises accuracy\nof attack moves\nduring one battle.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/5\/","name":"ruby-sapphire"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}}],"id":60,"machines":[],"fling_power":30}

=== Kirin92/ditto/data/api/v2/item/615/index.json
{
    "attributes": [],
    "baby_trigger_for": null,
    "category": {
        "name": "event-items",
        "url": "http://127.0.0.1:8000/api/v2/item-category/20/"
    },
    "cost": 0,
    "effect_entries": [
        {
            "effect": "Allows passage on the castelia city ship, which leads to liberty garden and victini.",
            "language": {
                "name": "en",
                "url": "http://127.0.0.1:8000/api/v2/language/9/"
            },
            "short_effect": "Allows access to Liberty Garden and Victini."
        }
    ],
    "flavor_text_entries": [
        {
            "language": {
                "name": "ja-kanji",
                "url": "http://127.0.0.1:8000/api/v2/language/11/"
            },
            "text": "\u30ea\u30d0\u30c6\u30a3\u30ac\u30fc\u30c7\u30f3\u5cf6\u306b\u3000\u884c\u304f\u305f\u3081\u306e\n\u7279\u5225\u306a\u3000\u30c1\u30b1\u30c3\u30c8\u3002\n\u30d2\u30a6\u30f3\u30b7\u30c6\u30a3\u304b\u3089\u3000\u8239\u306b\u3000\u4e57\u308c\u308b\u3002",
            "version_group": {
                "name": "x-y",
                "url": "http://127.0.0.1:8000/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "en",
                "url": "http://127.0.0.1:8000/api/v2/language/9/"
            },
            "text": "A special pass to go to Liberty Garden.\nBoard the ship in Castelia City.",
            "version_group": {
                "name": "x-y",
                "url": "http://127.0.0.1:8000/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "it",
                "url": "http://127.0.0.1:8000/api/v2/language/8/"
            },
            "text": "Biglietto speciale per l\u2019Isola Libert\u00e0.\nLa nave parte da Austropoli.",
            "version_group": {
                "name": "x-y",
                "url": "http://127.0.0.1:8000/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "es",
                "url": "http://127.0.0.1:8000/api/v2/language/7/"
            },
            "text": "Aumenta ligeramente la Velocidad en combate.\nAl cambiar de Pok\u00e9mon, el efecto desaparece.",
            "version_group": {
                "name": "x-y",
                "url": "http://127.0.0.1:8000/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "de",
                "url": "http://127.0.0.1:8000/api/v2/language/6/"
            },
            "text": "Ein besonderes Ticket f\u00fcr die \u00dcberfahrt von\nStratos City zur Insel des Freiheitsgartens.",
            "version_group": {
                "name": "x-y",
                "url": "http://127.0.0.1:8000/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "fr",
                "url": "http://127.0.0.1:8000/api/v2/language/5/"
            },
            "text": "Un ticket sp\u00e9cial permettant de se rendre sur\nl\u2019\u00cele Libert\u00e9 \u00e0 bord du bateau de Volucit\u00e9.",
            "version_group": {
                "name": "x-y",
                "url": "http://127.0.0.1:8000/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "ko",
                "url": "http://127.0.0.1:8000/api/v2/language/3/"
            },
            "text": "\ub9ac\ubc84\ud2f0\uac00\ub4e0\uc12c\uc5d0 \uac00\uae30 \uc704\ud55c\n\ud2b9\ubcc4\ud55c \ud2f0\ucf13.\n\uad6c\ub984\uc2dc\ud2f0\uc5d0\uc11c \ubc30\ub97c \ud0c8 \uc218 \uc788\ub2e4.",
            "version_group": {
                "name": "x-y",
                "url": "http://127.0.0.1:8000/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "ja",
                "url": "http://127.0.0.1:8000/api/v2/language/1/"
            },
            "text": "\u30ea\u30d0\u30c6\u30a3\u30ac\u30fc\u30c7\u30f3\u3068\u3046\u306b\u3000\u3044\u304f\u305f\u3081\u306e\n\u3068\u304f\u3079\u3064\u306a\u3000\u30c1\u30b1\u30c3\u30c8\u3002\n\u30d2\u30a6\u30f3\u30b7\u30c6\u30a3\u304b\u3089\u3000\u3075\u306d\u306b\u3000\u306e\u308c\u308b\u3002",
            "version_group": {
                "name": "x-y",
                "url": "http://127.0.0.1:8000/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "en",
                "url": "http://127.0.0.1:8000/api/v2/language/9/"
            },
            "text": "A special pass to go to Liberty Garden.\nBoard the ship in Castelia City.",
            "version_group": {
                "name": "black-2-white-2",
                "url": "http://127.0.0.1:8000/api/v2/version-group/14/"
            }
        },
        {
            "language": {
                "name": "en",
                "url": "http://127.0.0.1:8000/api/v2/language/9/"
            },
            "text": "A special pass to go to Liberty Garden.\nBoard the ship in Castelia City.",
            "version_group": {
                "name": "black-white",
                "url": "http://127.0.0.1:8000/api/v2/version-group/11/"
            }
        },
        {
            "language": {
                "name": "fr",
                "url": "http://127.0.0.1:8000/api/v2/language/5/"
            },
            "text": "Ticket sp\u00e9cial permettant de se\nrendre sur l\u2019\u00cele Libert\u00e9 \u00e0 bord\ndu bateau de Volucit\u00e9.",
            "version_group": {
                "name": "black-white",
                "url": "http://127.0.0.1:8000/api/v2/version-group/11/"
            }
        }
    ],
    "fling_effect": null,
    "fling_power": null,
    "game_indices": [
        {
            "game_index": 574,
            "generation": {
                "name": "generation-vi",
                "url": "http://127.0.0.1:8000/api/v2/generation/6/"
            }
        },
        {
            "game_index": 574,
            "generation": {
                "name": "generation-v",
                "url": "http://127.0.0.1:8000/api/v2/generation/5/"
            }
        }
    ],
    "held_by_pokemon": [],
    "id": 615,
    "machines": [],
    "name": "liberty-pass",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://127.0.0.1:8000/api/v2/language/9/"
            },
            "name": "Liberty Pass"
        },
        {
            "language": {
                "name": "it",
                "url": "http://127.0.0.1:8000/api/v2/language/8/"
            },
            "name": "Liberticket"
        },
        {
            "language": {
                "name": "es",
                "url": "http://127.0.0.1:8000/api/v2/language/7/"
            },
            "name": "Tarjeta Libertad"
        },
        {
            "language": {
                "name": "de",
                "url": "http://127.0.0.1:8000/api/v2/language/6/"
            },
            "name": "Gartenpass"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://127.0.0.1:8000/api/v2/language/5/"
            },
            "name": "Pass Libert\u00e9"
        },
        {
            "language": {
                "name": "ko",
                "url": "http://127.0.0.1:8000/api/v2/language/3/"
            },
            "name": "\ub9ac\ubc84\ud2f0\ud2f0\ucf13"
        },
        {
            "language": {
                "name": "ja",
                "url": "http://127.0.0.1:8000/api/v2/language/1/"
            },
            "name": "\u30ea\u30d0\u30c6\u30a3\u30c1\u30b1\u30c3\u30c8"
        }
    ],
    "sprites": {
        "default": "http://127.0.0.1:8000/media/sprites/items/liberty-pass.png"
    }
}
