=== Kirin92/ditto/data/schema/v2/item/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "attributes": {
            "items": {
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "url"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "baby_trigger_for": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "properties": {
                        "url": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "url"
                    ],
                    "type": "object"
                }
            ]
        },
        "category": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "url"
            ],
            "type": "object"
        },
        "cost": {
            "type": "integer"
        },
        "effect_entries": {
            "items": {
                "properties": {
                    "effect": {
                        "type": "string"
                    },
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "short_effect": {
                        "type": "string"
                    }
                },
                "required": [
                    "effect",
                    "language",
                    "short_effect"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "flavor_text_entries": {
            "items": {
                "properties": {
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "text": {
                        "type": "string"
                    },
                    "version_group": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "language",
                    "text",
                    "version_group"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "fling_effect": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "url": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "name",
                        "url"
                    ],
                    "type": "object"
                }
            ]
        },
        "fling_power": {
            "type": [
                "integer",
                "null"
            ]
        },
        "game_indices": {
            "items": {
                "properties": {
                    "game_index": {
                        "type": "integer"
                    },
                    "generation": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "game_index",
                    "generation"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "held_by_pokemon": {
            "items": {
                "properties": {
                    "pokemon": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "version_details": {
                        "items": {
                            "properties": {
                                "rarity": {
                                    "type": "integer"
                                },
                                "version": {
                                    "properties": {
                                        "name": {
                                            "type": "string"
                                        },
                                        "url": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "name",
                                        "url"
                                    ],
                                    "type": "object"
                                }
                            },
                            "required": [
                                "rarity",
                                "version"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    }
                },
                "required": [
                    "pokemon",
                    "version_details"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "id": {
            "type": "integer"
        },
        "machines": {
            "items": {
                "properties": {
                    "machine": {
                        "properties": {
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "url"
                        ],
                        "type": "object"
                    },
                    "version_group": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    }
                },
                "required": [
                    "machine",
                    "version_group"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "properties": {
                    "language": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "url": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "url"
                        ],
                        "type": "object"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "sprites": {
            "properties": {
                "default": {
                    "type": "string"
                }
            },
            "required": [
                "default"
            ],
            "type": "object"
        }
    },
    "required": [
        "attributes",
        "baby_trigger_for",
        "category",
        "cost",
        "effect_entries",
        "flavor_text_entries",
        "fling_effect",
        "fling_power",
        "game_indices",
        "held_by_pokemon",
        "id",
        "machines",
        "name",
        "names",
        "sprites"
    ],
    "type": "object"
}

=== Kirin92/ditto/data/api/v2/item/302/index.json
{
    "attributes": [],
    "baby_trigger_for": null,
    "category": {
        "name": "evolution",
        "url": "http://localhost/api/v2/item-category/10/"
    },
    "cost": 2100,
    "effect_entries": [
        {
            "effect": "Held by Dusclops: Evolves the holder into Dusknoir when traded.",
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "short_effect": "Traded on a Dusclops: Holder evolves into Dusknoir."
        }
    ],
    "flavor_text_entries": [
        {
            "language": {
                "name": "ja-kanji",
                "url": "http://localhost/api/v2/language/11/"
            },
            "text": "\u304a\u305d\u308d\u3057\u304f\u3000\u5f37\u3044\u3000\u970a\u529b\u304c\n\u3053\u3081\u3089\u308c\u3066\u3044\u308b\u3000\u5e03\u3002\n\u3042\u308b\u3000\u30dd\u30b1\u30e2\u30f3\u304c\u3000\u597d\u3093\u3067\u3044\u308b\u3002",
            "version_group": {
                "name": "x-y",
                "url": "http://localhost/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "text": "A cloth imbued with horrifyingly\nstrong spiritual energy.\nIt\u2019s loved by a certain Pok\u00e9mon.",
            "version_group": {
                "name": "x-y",
                "url": "http://localhost/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "it",
                "url": "http://localhost/api/v2/language/8/"
            },
            "text": "Panno intriso di un\u2019energia spirituale terribilmente\nforte. Piace a un Pok\u00e9mon in particolare.",
            "version_group": {
                "name": "x-y",
                "url": "http://localhost/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "es",
                "url": "http://localhost/api/v2/language/7/"
            },
            "text": "Ataca al objetivo con un potente rayo, pero quien\nlo usa debe descansar en el siguiente turno para\nreponer energ\u00eda.",
            "version_group": {
                "name": "x-y",
                "url": "http://localhost/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "de",
                "url": "http://localhost/api/v2/language/6/"
            },
            "text": "Ein Stoffumhang mit geistiger Energie.\nDas Lieblingsst\u00fcck eines bestimmten Pok\u00e9mon.",
            "version_group": {
                "name": "x-y",
                "url": "http://localhost/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "text": "Un tissu impr\u00e9gn\u00e9 d\u2019une \u00e9nergie spirituelle\nhorriblement puissante. Appr\u00e9ci\u00e9 d\u2019un certain\nPok\u00e9mon.",
            "version_group": {
                "name": "x-y",
                "url": "http://localhost/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "ko",
                "url": "http://localhost/api/v2/language/3/"
            },
            "text": "\ubb34\uc12d\uace0 \uac15\ud55c \uc601\ub825\uc774\n\ub2f4\uaca8 \uc788\ub294 \ucc9c.\n\uc5b4\ub5a4 \ud3ec\ucf13\ubaac\uc774 \uc88b\uc544\ud558\ub294 \ubb3c\uac74\uc774\ub2e4.",
            "version_group": {
                "name": "x-y",
                "url": "http://localhost/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "ja",
                "url": "http://localhost/api/v2/language/1/"
            },
            "text": "\u304a\u305d\u308d\u3057\u304f\u3000\u3064\u3088\u3044\u3000\u308c\u3044\u308a\u3087\u304f\u304c\n\u3053\u3081\u3089\u308c\u3066\u3044\u308b\u3000\u306c\u306e\u3002\n\u3042\u308b\u3000\u30dd\u30b1\u30e2\u30f3\u304c\u3000\u3053\u306e\u3093\u3067\u3044\u308b\u3002",
            "version_group": {
                "name": "x-y",
                "url": "http://localhost/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "text": "A cloth imbued with horrifyingly strong\nspiritual energy.\nIt is loved by a certain Pok\u00e9mon.",
            "version_group": {
                "name": "black-2-white-2",
                "url": "http://localhost/api/v2/version-group/14/"
            }
        },
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "text": "A cloth imbued with horrifyingly strong\nspiritual energy.\nIt is loved by a certain Pok\u00e9mon.",
            "version_group": {
                "name": "black-white",
                "url": "http://localhost/api/v2/version-group/11/"
            }
        },
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "text": "Un tissu impr\u00e9gn\u00e9 d\u2019une \u00e9nergie\nspirituelle horriblement puissante.\nAppr\u00e9ci\u00e9 d\u2019un certain Pok\u00e9mon.",
            "version_group": {
                "name": "black-white",
                "url": "http://localhost/api/v2/version-group/11/"
            }
        },
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "text": "A cloth imbued with horrifyingly strong\nspiritual energy.\nIt is loved by a certain Pok\u00e9mon.",
            "version_group": {
                "name": "heartgold-soulsilver",
                "url": "http://localhost/api/v2/version-group/10/"
            }
        },
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "text": "A cloth imbued with horrifyingly strong\nspiritual energy.\nIt is loved by a certain Pok\u00e9mon.",
            "version_group": {
                "name": "platinum",
                "url": "http://localhost/api/v2/version-group/9/"
            }
        },
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "text": "A cloth imbued with horrifyingly strong\nspiritual energy.\nIt is loved by a certain Pok\u00e9mon.",
            "version_group": {
                "name": "diamond-pearl",
                "url": "http://localhost/api/v2/version-group/8/"
            }
        }
    ],
    "fling_effect": null,
    "fling_power": 10,
    "game_indices": [
        {
            "game_index": 325,
            "generation": {
                "name": "generation-vi",
                "url": "http://localhost/api/v2/generation/6/"
            }
        },
        {
            "game_index": 325,
            "generation": {
                "name": "generation-v",
                "url": "http://localhost/api/v2/generation/5/"
            }
        },
        {
            "game_index": 325,
            "generation": {
                "name": "generation-iv",
                "url": "http://localhost/api/v2/generation/4/"
            }
        }
    ],
    "held_by_pokemon": [],
    "id": 302,
    "machines": [],
    "name": "reaper-cloth",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "Reaper Cloth"
        },
        {
            "language": {
                "name": "it",
                "url": "http://localhost/api/v2/language/8/"
            },
            "name": "Terrorpanno"
        },
        {
            "language": {
                "name": "es",
                "url": "http://localhost/api/v2/language/7/"
            },
            "name": "Tela Terrible"
        },
        {
            "language": {
                "name": "de",
                "url": "http://localhost/api/v2/language/6/"
            },
            "name": "D\u00fcsterumhang"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "name": "Tissu Fauche"
        },
        {
            "language": {
                "name": "ko",
                "url": "http://localhost/api/v2/language/3/"
            },
            "name": "\uc601\uacc4\uc758\ucc9c"
        },
        {
            "language": {
                "name": "ja",
                "url": "http://localhost/api/v2/language/1/"
            },
            "name": "\u308c\u3044\u304b\u3044\u306e\u306c\u306e"
        }
    ],
    "sprites": {
        "default": "http://localhost/media/sprites/items/reaper-cloth.png"
    }
}

=== Kirin92/ditto/api/v2/item/248/index.json
{"category":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/item-category\/12\/","name":"held-items"},"name":"power-herb","fling_effect":null,"effect_entries":[{"short_effect":"Held: Both turns of a two-turn charge move happen at once. Consumed upon use.","effect":"Held: Whenever the holder uses a move that requires a turn to charge first (Bounce, Dig, Dive, Fly, Razor Wind, Skull Bash, Sky Attack, or Solarbeam), this item is consumed and the charge is skipped.  Skull Bash still provides a Defense boost.","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}}],"held_by_pokemon":[],"sprites":{"default":"http:\/\/127.0.0.1:8000\/media\/sprites\/items\/power-herb.png"},"game_indices":[{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/6\/","name":"generation-vi"},"game_index":271},{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/5\/","name":"generation-v"},"game_index":271},{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/4\/","name":"generation-iv"},"game_index":271}],"baby_trigger_for":null,"cost":100,"names":[{"name":"Power Herb","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"name":"Vigorerba","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/8\/","name":"it"}},{"name":"Hierba \u00danica","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/7\/","name":"es"}},{"name":"Energiekraut","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/6\/","name":"de"}},{"name":"Herbe Pouvoir","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}},{"name":"\ud30c\uc6cc\ud480\ud5c8\ube0c","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/3\/","name":"ko"}},{"name":"\u30d1\u30ef\u30d5\u30eb\u30cf\u30fc\u30d6","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/1\/","name":"ja"}}],"attributes":[{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/item-attribute\/5\/","name":"holdable"},{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/item-attribute\/7\/","name":"holdable-active"}],"flavor_text_entries":[{"text":"\u6301\u305f\u305b\u305f\u3000\u30dd\u30b1\u30e2\u30f3\u306f\u3000\uff11\u5ea6\u3060\u3051\n\uff11\u30bf\u30fc\u30f3\u76ee\u306b\u3000\u3061\u304b\u3089\u3092\u3000\u305f\u3081\u308b\u6280\u3092\n\u3059\u3050\u306b\u3000\u4f7f\u3046\u3053\u3068\u304c\u3000\u3067\u304d\u308b\u3002","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/11\/","name":"ja-kanji"}},{"text":"A single-use item to be held by a Pok\u00e9mon.\nIt allows the holder to immediately use a\nmove that normally requires a turn to charge.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"Strumento monouso da dare a un Pok\u00e9mon.\nPermette l\u2019uso immediato di una mossa che in\ngenere richiede un turno prima di essere eseguita.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/8\/","name":"it"}},{"text":"Da\u00f1a en cada turno al Pok\u00e9mon que la lleva.\nPuede adherirse al Pok\u00e9mon que alcance con su\nataque al portador.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/7\/","name":"es"}},{"text":"Ein Item zum einmaligen Tragen. Der Tr\u00e4ger kann\ndadurch eine Attacke sofort einsetzen, die sonst\naufgeladen werden muss.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/6\/","name":"de"}},{"text":"Objet \u00e0 tenir et \u00e0 usage unique. Permet d\u2019utiliser\nimm\u00e9diatement une capacit\u00e9 qui devrait se\ncharger au premier tour.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}},{"text":"\uc9c0\ub2c8\uac8c \ud55c \ud3ec\ucf13\ubaac\uc740 \ud55c \ubc88\ub9cc\n1\ud134\uc9f8\uc5d0 \ud798\uc744 \ubaa8\uc73c\ub294 \uae30\uc220\uc744\n\ubc14\ub85c \uc0ac\uc6a9\ud560 \uc218\uac00 \uc788\ub2e4.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/3\/","name":"ko"}},{"text":"\u3082\u305f\u305b\u305f\u3000\u30dd\u30b1\u30e2\u30f3\u306f\u3000\u3044\u3061\u3069\u3060\u3051\n\uff11\u30bf\u30fc\u30f3\u3081\u306b\u3000\u3061\u304b\u3089\u3092\u3000\u305f\u3081\u308b\u308f\u3056\u3092\n\u3059\u3050\u306b\u3000\u3064\u304b\u3046\u3053\u3068\u304c\u3000\u3067\u304d\u308b\u3002","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/15\/","name":"x-y"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/1\/","name":"ja"}},{"text":"A single-use item to be held by a\nPok\u00e9mon. It allows the immediate use of\na move that charges on the first turn.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/14\/","name":"black-2-white-2"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"A single-use item to be held by a\nPok\u00e9mon. It allows the immediate use of\na move that charges on the first turn.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/11\/","name":"black-white"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"Objet \u00e0 tenir et \u00e0 usage unique. Permet\nd\u2019utiliser imm\u00e9diatement une capacit\u00e9\nqui devrait se charger au premier tour.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/11\/","name":"black-white"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}},{"text":"A single-use item to be held by a\nPok\u00e9mon. It allows the immediate use of\na move that charges on the first turn.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/10\/","name":"heartgold-soulsilver"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"A single-use item to be held by a\nPok\u00e9mon. It allows the immediate use of\na move that charges on the first turn.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/9\/","name":"platinum"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"A single-use item to be held by a\nPok\u00e9mon. It allows the immediate use of\na move that charges on the first turn.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/8\/","name":"diamond-pearl"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}}],"id":248,"machines":[],"fling_power":10}

=== Kirin92/ditto/api/v2/item/546/index.json
{"category":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/item-category\/22\/","name":"plot-advancement"},"name":"gold-teeth","fling_effect":null,"effect_entries":[{"short_effect":"The Safari Zone Warden's dentures. Trade for HM04 (Strength).","effect":"The Safari Zone warden's teeth, to be returned to him for hm04.","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}}],"held_by_pokemon":[],"sprites":{"default":"http:\/\/127.0.0.1:8000\/media\/sprites\/items\/gold-teeth.png"},"game_indices":[{"generation":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/generation\/3\/","name":"generation-iii"},"game_index":353}],"baby_trigger_for":null,"cost":0,"names":[{"name":"Gold Teeth","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"name":"Denti d'Oro","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/8\/","name":"it"}},{"name":"Dientes Oro","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/7\/","name":"es"}},{"name":"Goldz\u00e4hne","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/6\/","name":"de"}},{"name":"Dent d'Or","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/5\/","name":"fr"}},{"name":"\u304d\u3093\u306e\u3044\u308c\u3070","language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/1\/","name":"ja"}}],"attributes":[],"flavor_text_entries":[{"text":"A set of false teeth lost by the\nSAFARI ZONE\u2019S WARDEN. It makes his\nsmile sparkle.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/7\/","name":"firered-leafgreen"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}},{"text":"Gold dentures lost\nby the SAFARI\nZONE\u2019s WARDEN.","version_group":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/version-group\/6\/","name":"emerald"},"language":{"url":"http:\/\/127.0.0.1:8000\/api\/v2\/language\/9\/","name":"en"}}],"id":546,"machines":[],"fling_power":null}
